"""The deterministic Dictation score, computed by the server (D-103.2, D4 I18).

A port of `static/orena/capabilities/dictation-evaluator.js#evaluateListeningReconstruction`. The
browser still grades for instant feedback; the score that is STORED is this one, because a number a
client sends cannot be verified. Parity with the browser is proved by one golden-vector file
generated by running the JavaScript (`tests/fixtures/dictation_golden.json`), consumed here by
`tests/test_dictation_evaluator.py` and by `scripts/test_dictation_golden.mjs`, so drift on either
side fails CI.

JavaScript's `\\p{L}`, `\\p{N}` and `Script=Han` have no `re` equivalent, so the tokenizer classifies
with `unicodedata` general categories (L*, N*) and explicit Han ranges. The size limit counts UTF-16
code units, as the browser's `String.length` does, and the percentage rounds half up, as
`Math.round` does (Python's `round` would round half to even).
"""
from __future__ import annotations

import math
import unicodedata

MAX_LISTENING_RECONSTRUCTION_CHARS = 2000
MAX_LISTENING_EVALUATION_UNITS = 500


class ListeningPracticeError(Exception):
    """A refused evaluation; `code` is the browser evaluator's own stable code."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


# JavaScript `\s` (with the u flag) and String.prototype.trim: WhiteSpace and LineTerminator.
_SPACE = frozenset(
    "\t\n\v\f\r              "
    "    　﻿"
)

# Unicode `Script=Han`: ideographs and the radicals, ideographic number marks and iteration marks
# the script property covers.
_HAN_RANGES = (
    (0x2E80, 0x2E99), (0x2E9B, 0x2EF3), (0x2F00, 0x2FD5), (0x3005, 0x3005), (0x3007, 0x3007),
    (0x3021, 0x3029), (0x3038, 0x303B), (0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFA6D),
    (0xFA70, 0xFAD9), (0x16FE2, 0x16FE3), (0x16FF0, 0x16FF1), (0x20000, 0x2A6DF),
    (0x2A700, 0x2B739), (0x2B740, 0x2B81D), (0x2B820, 0x2CEA1), (0x2CEB0, 0x2EBE0),
    (0x2F800, 0x2FA1D), (0x30000, 0x3134A), (0x31350, 0x323AF),
)


def _is_han(char: str) -> bool:
    code = ord(char)
    return any(low <= code <= high for low, high in _HAN_RANGES)


def _is_letter_or_number(char: str) -> bool:
    return unicodedata.category(char)[0] in ("L", "N")


def _collapse_and_trim(text: str) -> str:
    out: list[str] = []
    pending_space = False
    for char in text:
        if char in _SPACE:
            pending_space = True
            continue
        if pending_space and out:
            out.append(" ")
        pending_space = False
        out.append(char)
    return "".join(out)


def normalized_text(value: object) -> str:
    text = "" if value is None else str(value)
    text = unicodedata.normalize("NFKC", text)
    for char in "‘’ʼ":
        text = text.replace(char, "'")
    text = "".join("-" if 0x2010 <= ord(char) <= 0x2015 or char == "−" else char for char in text)
    return _collapse_and_trim(text)


def _word_run(text: str, start: int) -> int:
    """End of `[\\p{L}\\p{N}]+(?:['-][\\p{L}\\p{N}]+)*` starting at `start` (which must begin a run)."""
    end = start
    while end < len(text) and _is_letter_or_number(text[end]):
        end += 1
    while (
        end + 1 < len(text)
        and text[end] in ("'", "-")
        and _is_letter_or_number(text[end + 1])
    ):
        end += 1
        while end < len(text) and _is_letter_or_number(text[end]):
            end += 1
    return end


def listening_units(value: object, source_language: str) -> list[str]:
    normalized = normalized_text(value)
    zh = source_language == "zh"
    text = normalized if zh else normalized.lower()
    units: list[str] = []
    position = 0
    while position < len(text):
        char = text[position]
        if zh and _is_han(char):
            units.append(char)
            position += 1
        elif _is_letter_or_number(char):
            end = _word_run(text, position)
            unit = text[position:end]
            units.append(unit if len(unit) == 1 and _is_han(unit) else unit.lower())
            position = end
        else:
            position += 1
    return units


def listening_edit_distance(expected: list[str], answer: list[str]) -> int:
    previous = list(range(len(answer) + 1))
    for row in range(1, len(expected) + 1):
        current = [row]
        for column in range(1, len(answer) + 1):
            substitution = previous[column - 1] + (0 if expected[row - 1] == answer[column - 1] else 1)
            current.append(min(previous[column] + 1, current[column - 1] + 1, substitution))
        previous = current
    return previous[len(answer)]


def _utf16_length(text: str) -> int:
    return len(text.encode("utf-16-le")) // 2


def evaluate_listening_reconstruction(*, source_language: str, expected: object, answer: object) -> dict:
    expected_text = normalized_text(expected)
    answer_text = normalized_text(answer)
    if not expected_text:
        raise ListeningPracticeError("canonical_empty", "The canonical transcript segment is empty.")
    if not answer_text:
        raise ListeningPracticeError("answer_empty", "Type what you heard before checking.")
    if _utf16_length(answer_text) > MAX_LISTENING_RECONSTRUCTION_CHARS:
        raise ListeningPracticeError("answer_too_large", "Your reconstruction is too long to check safely.")
    expected_units = listening_units(expected_text, source_language)
    answer_units = listening_units(answer_text, source_language)
    if not expected_units:
        raise ListeningPracticeError(
            "canonical_empty", "The canonical transcript segment has no comparable text."
        )
    if not answer_units:
        raise ListeningPracticeError("answer_empty", "Type what you heard before checking.")
    if (
        len(expected_units) > MAX_LISTENING_EVALUATION_UNITS
        or len(answer_units) > MAX_LISTENING_EVALUATION_UNITS
    ):
        raise ListeningPracticeError("evaluation_too_large", "This segment is too large to check safely.")
    distance = listening_edit_distance(expected_units, answer_units)
    denominator = max(len(expected_units), len(answer_units))
    ratio = max(0.0, min(1.0, 1 - distance / denominator))
    return {
        "accuracy_percent": math.floor(ratio * 100 + 0.5),
        "exact": distance == 0,
        "expected_unit_count": len(expected_units),
        "answer_unit_count": len(answer_units),
        "edit_distance": distance,
    }
