"""``apply-feedback`` (human, 2026-09-29, item 4): fold external-review feedback back into a level.

Input: several JSONL files of one level (``review_export.py`` says what a reviewer returns). Steps:

1. **Parse** each line (code fences and blank lines tolerated; a line that is not a JSON object with
   the five keys is recorded as unparsed, never fatal). ``block: "none"`` lines are the reviewer's
   "ok" markers and are dropped.
2. **De-duplicate**: feedback on the same point and block from different reviewers (or the same one
   twice) that says the same thing collapses into one item; the highest severity and every source
   are kept.
3. **Apply** per point and block: the flagged block alone is regenerated by the model from the
   current block plus the feedback (same schemas and assembly as ``generate``), written into a
   copy, and the whole set is validated again. A block whose regeneration introduces a validate
   issue is put back and reported as skipped with the codes. Feedback about the level as a whole,
   about a point's structural metadata, or about an approved point is left to the human.
4. **Log** which feedback was applied and which skipped, with the reason, to
   ``grammar_lab/review/<lang>/<level>.applied.json``.

Never sets ``status``: a point that took feedback stays what it was (a draft), and only a human
approves.
"""

from __future__ import annotations

import copy
import difflib
import json
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from grammar_lab.pipeline.content_store import load_functions, load_manifest, load_points, save_point
from grammar_lab.pipeline.generate import (
    _PATTERN_ROLES,
    _PINYIN_INSTRUCTION,
    _TIMELINE_SHAPES,
    _as_locale_map,
    _item_schemas_v04,
    _slots,
    assemble_common_mistake,
    assemble_compare_item,
    assemble_example,
    assemble_morphology_row,
    assemble_quick_practice_item,
    pinyin_from_pairs,
)
from grammar_lab.pipeline.jsonio import read_json
from grammar_lab.pipeline.llm_client import LLMClient, LLMError, LLMUsage
from grammar_lab.pipeline.review_export import ISSUE_TAGS, NO_ISSUE_BLOCK, SEVERITIES, review_path
from grammar_lab.pipeline.validate import ERROR_TAGS_PATH, LAB_ROOT, validate_lang

REQUIRED_KEYS = ("id", "block", "issue", "severity", "fix")
LEVEL_ID = "LEVEL"
SIMILARITY = 0.72  # two pieces of feedback on one block this alike are the same feedback
_BLOCK = re.compile(r"^([a-z_]+)(?:\[(\d+)\])?$")
_TAG = re.compile(r"^\s*\[([a-z]+)\]")
REGENERABLE = ("header", "pattern", "illustration", "when_to_use", "examples", "compare", "common_mistakes",
               "quick_practice", "personal_production")
_SEVERITY_RANK = {"blocker": 3, "major": 2, "minor": 1, "none": 0}
# rough size of one regeneration call, only for the dry-run cost estimate
_EST_TOKENS = (2500, 900)


@dataclass
class Feedback:
    id: str
    block: str
    issue: str
    severity: str
    fix: str
    sources: list[str] = field(default_factory=list)
    merged: int = 0

    @property
    def tag(self) -> str:
        found = _TAG.match(self.issue)
        return found.group(1) if found and found.group(1) in ISSUE_TAGS else "untagged"

    @property
    def kind(self) -> str:
        found = _BLOCK.match(self.block)
        return found.group(1) if found else self.block

    @property
    def index(self) -> int | None:
        found = _BLOCK.match(self.block)
        return int(found.group(2)) if found and found.group(2) is not None else None


@dataclass
class Outcome:
    item: Feedback
    status: str  # applied | skipped | merged
    reason: str = ""


# -- parse and de-duplicate ------------------------------------------------------------------
def parse_files(paths: list[Path]) -> tuple[list[Feedback], list[dict[str, str]]]:
    items: list[Feedback] = []
    unparsed: list[dict[str, str]] = []
    for path in paths:
        for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            line = raw.strip()
            if not line or line.startswith("```"):
                continue
            where = f"{path.name}:{number}"
            try:
                data = json.loads(line)
            except json.JSONDecodeError:
                unparsed.append({"where": where, "reason": "not JSON", "line": line[:200]})
                continue
            if not isinstance(data, dict) or any(key not in data for key in REQUIRED_KEYS):
                unparsed.append({"where": where, "reason": f"needs keys {list(REQUIRED_KEYS)}", "line": line[:200]})
                continue
            severity = str(data["severity"]).strip().lower()
            if data["block"] == NO_ISSUE_BLOCK or severity == "none":
                continue
            if severity not in SEVERITIES:
                unparsed.append({"where": where, "reason": f"severity {severity!r} not in {list(SEVERITIES)}", "line": line[:200]})
                continue
            items.append(Feedback(str(data["id"]), str(data["block"]).strip(), str(data["issue"]), severity,
                                  str(data["fix"] or ""), [where]))
    return items, unparsed


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", _TAG.sub("", text or "")).strip().casefold()


def _same(a: Feedback, b: Feedback) -> bool:
    if a.fix and b.fix and _norm(a.fix) == _norm(b.fix):
        return True
    text_a, text_b = _norm(a.issue + " " + a.fix), _norm(b.issue + " " + b.fix)
    return difflib.SequenceMatcher(None, text_a, text_b).ratio() >= SIMILARITY


def dedupe(items: list[Feedback]) -> tuple[list[Feedback], list[Outcome]]:
    kept: list[Feedback] = []
    merged: list[Outcome] = []
    for item in items:
        twin = next((k for k in kept if k.id == item.id and k.block == item.block and _same(k, item)), None)
        if twin is None:
            kept.append(item)
            continue
        if _SEVERITY_RANK[item.severity] > _SEVERITY_RANK[twin.severity]:
            twin.severity = item.severity
        if item.fix and len(item.fix) > len(twin.fix):
            twin.fix = item.fix
        twin.sources += item.sources
        twin.merged += 1
        merged.append(Outcome(item, "merged", f"same as {twin.sources[0]}"))
    return kept, merged


# -- block regeneration ----------------------------------------------------------------------
def _block_of(point: dict[str, Any], kind: str, index: int | None) -> Any:
    if kind in ("pattern", "illustration"):
        return point["pattern"]
    if kind in ("when_to_use", "examples", "compare", "common_mistakes", "quick_practice"):
        return point[kind][index] if index is not None else point[kind]
    return point.get(kind)


def _schema_for(kind: str, point: dict[str, Any], *, locales: list[str], l1s: list[str], engine_tags: list[str],
                zh: bool) -> dict[str, Any]:
    items = _item_schemas_v04(
        locales=locales, l1s=l1s, error_tags=point["error_tags"], engine_tags=engine_tags,
        contrast_with=point["contrasts"], zh=zh,
    )
    locale_map = items["locale_map"]
    pairs = items["pinyin_pairs"]
    if kind == "header":
        props = {"title": locale_map, "summary": locale_map, "sub": locale_map}
        block: dict[str, Any] = {"type": "object", "additionalProperties": False, "required": list(props), "properties": props}
    elif kind in ("pattern", "illustration"):
        props = {"formula": {"type": "array", "minItems": 1, "items": items["slot"]},
                 "negative": {"type": "array", "items": items["slot"]},
                 "question": {"type": "array", "items": items["slot"]}}
        if point["point_type"] == "tense_aspect":
            props["timeline_shape"] = {"enum": _TIMELINE_SHAPES}
        elif point["point_type"] == "morphology":
            props["morphology"] = {"type": "array", "minItems": 1, "maxItems": 4, "items": items["with_pinyin"](
                {"type": "object", "additionalProperties": False, "required": ["base", "affix", "result"],
                 "properties": {"base": {"type": "string"}, "affix": {"type": "string"}, "result": {"type": "string"}}},
                "base_pinyin_pairs", "affix_pinyin_pairs", "result_pinyin_pairs")}
        block = {"type": "object", "additionalProperties": False, "required": list(props), "properties": props}
    elif kind == "when_to_use":
        block = locale_map
    elif kind == "examples":
        block = items["example"]
    elif kind == "compare":
        block = items["compare_item"]
    elif kind == "common_mistakes":
        block = items["common_mistake"]
    elif kind == "quick_practice":
        block = items["quick_practice_item"]
    else:  # personal_production
        slot = {"type": "object", "additionalProperties": False, "required": ["role"],
                "properties": {"role": {"enum": _PATTERN_ROLES}, "any_of": {"type": "array", "items": {"type": "string"}},
                               "regex": {"type": "string"}}}
        props = {
            "prompt": locale_map, "placeholder": {"type": "string", "minLength": 1},
            "target_form": {"enum": ["affirmative", "negative", "question"]},
            "pattern_rule": {"type": "object", "additionalProperties": False, "required": ["ordered", "slots"],
                             "properties": {"ordered": {"type": "boolean"},
                                            "slots": {"type": "array", "minItems": 1, "items": slot}}},
            "sample": {"type": "string", "minLength": 1},
        }
        if zh:
            props["placeholder_pinyin_pairs"] = pairs
            props["sample_pinyin_pairs"] = pairs
        block = {"type": "object", "additionalProperties": False, "required": list(props), "properties": props}
    return {"type": "object", "additionalProperties": False, "required": ["block"], "properties": {"block": block}}


def _assemble(kind: str, raw: Any, point: dict[str, Any], old: Any, *, zh: bool, locales: list[str]) -> Any:
    def loc(value: Any) -> Any:
        return _as_locale_map(value, locales)

    if kind == "header":
        header = dict(point["header"])
        header.update(title=loc(raw["title"]), summary=loc(raw["summary"]), sub=loc(raw["sub"]))
        return header
    if kind in ("pattern", "illustration"):
        pattern: dict[str, Any] = {"formula": _slots(raw["formula"], zh, locales)}
        variants = {n: _slots(raw[n], zh, locales) for n in ("negative", "question") if raw.get(n)}
        if variants:
            pattern["variants"] = variants
        illustration: dict[str, Any] = {"kind": point["pattern"]["illustration"]["kind"]}
        if point["point_type"] == "tense_aspect":
            illustration["timeline"] = {**point["pattern"]["illustration"].get("timeline", {}), "shape": raw["timeline_shape"]}
        elif point["point_type"] == "morphology":
            illustration["morphology"] = [assemble_morphology_row(r, zh) for r in raw["morphology"]]
        pattern["illustration"] = illustration
        return pattern
    if kind == "when_to_use":
        return loc(raw)
    if kind == "examples":
        return assemble_example(raw, zh, loc)
    if kind == "compare":
        return assemble_compare_item(raw, zh, loc)
    if kind == "common_mistakes":
        return assemble_common_mistake(raw, zh, loc)
    if kind == "quick_practice":
        return assemble_quick_practice_item(raw, zh, loc)
    production = {
        "prompt": loc(raw["prompt"]), "placeholder": raw["placeholder"], "target_form": raw["target_form"],
        "pattern_rule": {"ordered": raw["pattern_rule"]["ordered"], "slots": [
            {key: value for key, value in slot.items() if value not in (None, [], "")} for slot in raw["pattern_rule"]["slots"]]},
        "sample": {"text": raw["sample"]},
    }
    if zh:
        production["placeholder_pinyin"] = pinyin_from_pairs(raw["placeholder_pinyin_pairs"])
        production["sample"]["pinyin"] = pinyin_from_pairs(raw["sample_pinyin_pairs"])
    if isinstance(old, dict) and old.get("placeholder_note"):
        production["placeholder_note"] = old["placeholder_note"]
    return production


def _put(point: dict[str, Any], kind: str, index: int | None, block: Any) -> None:
    if kind in ("pattern", "illustration"):
        point["pattern"] = block
    elif index is not None and kind in ("when_to_use", "examples", "compare", "common_mistakes", "quick_practice"):
        point[kind][index] = block
    else:
        point[kind] = block


SYSTEM = """\
You correct ONE block of a grammar point of the Orena language-learning app, following review feedback.

Point: {point_id} ({target_lang}, level {level}, point_type {point_type}, function {function}).
Learner: an adult Vietnamese speaker. Explanations are written in {locales}: a locale field is
{locale_format}
Engine error labels you may use for `error_tag`: {engine_tags}.
This point's own error tags: {error_tags}.

Rules:
- Change only what the feedback says is wrong; keep everything else of the block as it is.
- If a piece of feedback is itself mistaken (the block is already right), leave that part unchanged.
- Explanations stay clear, adult and unadorned; examples stay natural.
- Every wrong quick-practice option is a real learner error tagged with its engine label; exactly one
  option is correct and `answer` is its 0-based index.
- Give spans as the exact substring of the sentence and its role (never offsets).
{pinyin}
Return the corrected block as `block`."""


def _validate_issues(lang: str, root: Path, file: str) -> set[tuple[str, str]]:
    report = validate_lang(lang, root)
    return {(issue.code, issue.path) for issue in report.issues if issue.file == file}


@dataclass
class ApplyResult:
    outcomes: list[Outcome]
    unparsed: list[dict[str, str]]
    cost_usd: float
    calls: int


def apply_feedback(
    lang: str, level: str, files: list[Path], *, llm: LLMClient | None, root: Path = LAB_ROOT, dry_run: bool = False,
    allow_approved: bool = False, cost_ceiling_usd: float | None = None, log_dir: Path | None = None,
) -> ApplyResult:
    items, unparsed = parse_files(files)
    items, outcomes = dedupe(items)
    points = load_points(lang, root)
    manifest = load_manifest(lang, root)
    locales: list[str] = manifest["explanation_locales"]
    l1s: list[str] = manifest["l1"]
    functions = {f["id"]: f for f in load_functions(root)["functions"]}
    engine_tags = read_json(root / ERROR_TAGS_PATH)["languages"]["zh-Hans" if lang == "zh" else "en"]["tags"]
    zh = lang == "zh"

    groups: dict[tuple[str, str, int | None], list[Feedback]] = {}
    for item in items:
        if item.id == LEVEL_ID or item.kind == "catalogue":
            outcomes.append(Outcome(item, "skipped", "feedback about the whole level: for the human (catalogue)"))
        elif item.id not in points:
            outcomes.append(Outcome(item, "skipped", "no such point in this language"))
        elif item.kind == "metadata":
            outcomes.append(Outcome(item, "skipped", "structural metadata (function, level, prereqs, contrasts, tags): for the human"))
        elif item.kind not in REGENERABLE:
            outcomes.append(Outcome(item, "skipped", f"unknown block {item.block!r}"))
        elif points[item.id]["status"] == "approved" and not allow_approved:
            outcomes.append(Outcome(item, "skipped", "point is approved: pass --allow-approved to touch it"))
        else:
            key_kind = "pattern" if item.kind == "illustration" else item.kind
            groups.setdefault((item.id, key_kind, item.index), []).append(item)

    cost = 0.0
    calls = 0
    for (point_id, kind, index), group in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][1], kv[0][2] or 0)):
        point = points[point_id]
        file = f"content/{lang}/{point_id}.json"
        if kind not in ("header", "pattern", "personal_production") and index is None:
            for item in group:
                outcomes.append(Outcome(item, "skipped", f"{kind} needs an index, e.g. {kind}[0]"))
            continue
        if kind == "personal_production" and "personal_production" not in point:
            for item in group:
                outcomes.append(Outcome(item, "skipped", "the point has no personal_production block"))
            continue
        try:
            old = _block_of(point, kind, index)
        except (IndexError, KeyError):
            for item in group:
                outcomes.append(Outcome(item, "skipped", f"no {kind}[{index}] in the point"))
            continue
        if dry_run:
            est = LLMUsage(*_EST_TOKENS).cost_usd(llm.model) if llm else None
            cost += est or 0.0
            calls += 1
            for item in group:
                outcomes.append(Outcome(item, "planned", f"would regenerate {kind}" + (f"[{index}]" if index is not None else "")))
            continue
        if llm is None:
            raise ValueError("apply_feedback needs an LLM unless dry_run")
        if cost_ceiling_usd is not None and cost >= cost_ceiling_usd:
            for item in group:
                outcomes.append(Outcome(item, "skipped", f"cost ceiling ${cost_ceiling_usd} reached"))
            continue
        schema = _schema_for(kind, point, locales=locales, l1s=l1s, engine_tags=engine_tags, zh=zh)
        system = SYSTEM.format(
            point_id=point_id, target_lang=point["target_lang"], level=point["level"]["value"],
            point_type=point["point_type"], function=functions.get(point["function"], {}).get("title", {}).get("en", point["function"]),
            locales=", ".join(locales), engine_tags=", ".join(engine_tags), error_tags=", ".join(point["error_tags"]),
            locale_format=(f"a plain string in `{locales[0]}`" if len(locales) == 1
                           else "an object with every one of the keys " + ", ".join(locales) + "."),
            pinyin=_PINYIN_INSTRUCTION if zh else "",
        )
        feedback_text = "\n".join(
            f"- [{item.severity}] {item.issue}" + (f"\n  suggested fix: {item.fix}" if item.fix else "") for item in group
        )
        user = f"Current block `{kind}`" + (f"[{index}]" if index is not None else "") + ":\n" + \
            json.dumps(old, ensure_ascii=False, indent=1) + f"\n\nReview feedback:\n{feedback_text}\n"
        problems = ""
        applied = False
        for _attempt in range(2):
            try:
                result = llm.complete(system=system, user=user + problems, json_schema=schema,
                                      schema_name=f"regenerate_{kind}", max_tokens=6000)
            except LLMError as exc:
                for item in group:
                    outcomes.append(Outcome(item, "skipped", f"model call failed: {exc}"))
                break
            calls += 1
            cost += result.usage.cost_usd(result.model) or 0.0
            try:
                new_block = _assemble(kind, result.data["block"], point, old, zh=zh, locales=locales)
            except (KeyError, TypeError, ValueError) as exc:
                problems = f"\nYour previous answer could not be used ({exc}). Return the block again.\n"
                continue
            before = _validate_issues(lang, root, file)
            candidate = copy.deepcopy(point)
            _put(candidate, kind, index, new_block)
            save_point(lang, candidate, root)
            new_issues = _validate_issues(lang, root, file) - before
            if not new_issues:
                candidate.setdefault("provenance", {}).setdefault("feedback", []).append({
                    "block": kind + (f"[{index}]" if index is not None else ""),
                    "applied_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "model": f"{result.provider}:{result.model}", "issues": len(group),
                    "sources": sorted({src for item in group for src in item.sources}),
                })
                save_point(lang, candidate, root)
                points[point_id] = candidate
                for item in group:
                    outcomes.append(Outcome(item, "applied", f"{kind} regenerated"))
                applied = True
                break
            save_point(lang, point, root)  # put the old block back
            problems = "\nYour previous answer failed these checks, fix them:\n" + "\n".join(
                f"- {code} at {path}" for code, path in sorted(new_issues)) + "\n"
        else:
            for item in group:
                outcomes.append(Outcome(item, "skipped", "regeneration kept failing validate: " + problems.strip().replace("\n", " ")[:300]))
        if not applied and not any(o.item in group for o in outcomes):
            for item in group:
                outcomes.append(Outcome(item, "skipped", "no usable regeneration"))
    if not dry_run:
        write_log(lang, level, files, outcomes, unparsed, cost, calls, log_dir)
    return ApplyResult(outcomes, unparsed, cost, calls)


def write_log(lang: str, level: str, files: list[Path], outcomes: list[Outcome], unparsed: list[dict[str, str]],
              cost: float, calls: int, log_dir: Path | None = None) -> Path:
    path = (review_path(lang, level, log_dir) if log_dir else review_path(lang, level)).with_suffix(".applied.json")
    entries = [
        {"id": o.item.id, "block": o.item.block, "tag": o.item.tag, "severity": o.item.severity, "issue": o.item.issue,
         "fix": o.item.fix, "sources": o.item.sources, "status": o.status, "reason": o.reason}
        for o in outcomes
    ]
    previous = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"runs": []}
    previous["runs"].append({
        "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "files": [f.name for f in files],
        "cost_usd": round(cost, 6), "model_calls": calls, "unparsed": unparsed,
        "applied": [e for e in entries if e["status"] == "applied"],
        "skipped": [e for e in entries if e["status"] == "skipped"],
        "merged": [e for e in entries if e["status"] == "merged"],
    })
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(previous, ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")
    return path


def feedback_stats(items: list[Feedback]) -> dict[str, Any]:
    """Counts by issue type (knowledge / scope / wording / format), severity, block kind and point."""
    def count(key: Any) -> dict[str, int]:
        out: dict[str, int] = {}
        for item in items:
            out[key(item)] = out.get(key(item), 0) + 1
        return dict(sorted(out.items(), key=lambda kv: -kv[1]))

    return {
        "total": len(items),
        "by_type": count(lambda i: i.tag),
        "by_severity": count(lambda i: i.severity),
        "by_block": count(lambda i: i.kind),
        "by_point": count(lambda i: i.id),
    }
