"""Canonical catalog v1 -> Grammar Lab's runtime catalogue (``inventory/catalog_<lang>.yaml``).

``inventory/canonical_v1/{en,zh}.yaml`` is the locked syllabus (see its README): what points exist, at
which level, with which R5 provenance and GF0025 source items. It is not the runtime shape. This module
converts it, deterministically and idempotently, into the seed-schema records ``generate`` and
``coverage`` read (``seed.load_catalog``):

- membership, level, R5 sources/aliases and GF0025 refs come from the canonical file only;
- pedagogical metadata (function, point_type, titles, error_tags, contrasts, prereqs, sequence,
  anchors) is carried over from the human-reviewed ``seeds_<lang>.yaml`` when the id overlaps, and
  marked ``metadata_origin: reviewed_seed``;
- everything else gets the default-safe values below, marked ``metadata_origin: default_safe`` so no
  reader mistakes it for reviewed metadata. Nothing here calls a model.
"""

from __future__ import annotations

from functools import cache
from pathlib import Path
from typing import Any

import yaml

from grammar_lab.pipeline.jsonio import read_yaml
from grammar_lab.pipeline.validate import LAB_ROOT

CATALOG_VERSION = 1
DEFAULT_FUNCTION = "fn.catalog_unclassified"
DEFAULT_POINT_TYPE = "other"
DEFAULT_ERROR_TAGS = ["other"]
DEFAULT_BATCH = "canonical_v1"
HEADER = (
    "# GENERATED by `python -m grammar_lab.pipeline.cli import-canonical` from inventory/canonical_v1/ and\n"
    "# inventory/seeds_<lang>.yaml. Do not edit by hand: change the source and re-run the importer.\n"
)
# Reviewed-seed fields carried over verbatim when the canonical id overlaps a seed.
SEED_FIELDS = ("function", "point_type", "native_title", "title", "error_tags", "contrasts", "prereqs", "sequence", "anchors", "batch")


def canonical_dir(root: Path = LAB_ROOT) -> Path:
    return root / "inventory" / "canonical_v1"


def catalog_path(lang: str, root: Path = LAB_ROOT) -> Path:
    return root / "inventory" / f"catalog_{lang}.yaml"


def load_canonical(lang: str, root: Path = LAB_ROOT) -> dict[str, Any]:
    return read_yaml(canonical_dir(root) / f"{lang}.yaml")


def scale_value(lang: str, canonical_level: str) -> str:
    """The value on the language's level scale: ``HSK3`` -> ``3``, ``A2`` -> ``A2``."""
    return canonical_level.removeprefix("HSK") if lang == "zh" else canonical_level


def _reviewed_seeds(lang: str, root: Path) -> dict[str, dict[str, Any]]:
    path = root / "inventory" / f"seeds_{lang}.yaml"
    seeds = read_yaml(path) or [] if path.exists() else []
    return {seed["id"]: seed for seed in seeds}


def build_catalog(lang: str, root: Path = LAB_ROOT) -> list[dict[str, Any]]:
    """The runtime catalogue, in canonical order. Pure function of the canonical file and the seeds."""
    seeds = _reviewed_seeds(lang, root)
    items = load_canonical(lang, root)["items"]
    next_sequence: dict[str, int] = {}
    records: list[dict[str, Any]] = []
    for item in items:
        level = scale_value(lang, item["level"])
        seed = seeds.get(item["id"])
        catalog: dict[str, Any] = {
            "version": CATALOG_VERSION,
            "canonical_level": item["level"],
            "official_band": item.get("official_band", item["level"]),
            "level_origin": item.get("level_origin", ""),
            "origin": item.get("origin", "r5_reused"),
            "conversion": item["conversion"],
            "research_candidate_id": item.get("research_candidate_id"),
            "source_items": list(item.get("source_items", [])),
            "source_scope": list(item.get("source_scope", [])),
            "category_path": list(item.get("category_path", [])),
            "notes": list(item.get("notes", []) or item.get("conversion_notes", [])),
        }
        catalog = {key: value for key, value in catalog.items() if value not in (None, [], "")}
        if seed is not None:
            record = {"id": item["id"], "level": level, **{key: seed[key] for key in SEED_FIELDS}}
            catalog["metadata_origin"] = "reviewed_seed"
            if str(seed["level"]) != level:
                catalog["seed_level_overridden"] = str(seed["level"])
        else:
            sequence = next_sequence.get(level, 0) + 1
            next_sequence[level] = sequence
            record = {
                "id": item["id"], "level": level, "function": DEFAULT_FUNCTION, "point_type": DEFAULT_POINT_TYPE,
                # a placeholder in the required explanation locale, never a translation: generate rewrites it
                "native_title": item["title"], "title": {"vi": item["title"]},
                "error_tags": list(DEFAULT_ERROR_TAGS), "contrasts": [], "prereqs": [], "sequence": sequence,
                "anchors": [], "batch": DEFAULT_BATCH,
            }
            catalog["metadata_origin"] = "default_safe"
            catalog["title_origin"] = "canonical_title_untranslated"
        record["r5"] = list(item.get("r5_sources", []))
        record["aliases"] = list(item.get("r5_aliases", []))
        if catalog["origin"].startswith("gf0025") or catalog.get("source_items"):
            record["gf0025"] = list(item.get("source_items", []))
        record["catalog"] = catalog
        records.append(record)
    return records


def render_catalog(records: list[dict[str, Any]]) -> str:
    return HEADER + yaml.safe_dump(records, allow_unicode=True, sort_keys=False, width=120)


def write_catalog(lang: str, root: Path = LAB_ROOT) -> bool:
    """Write ``inventory/catalog_<lang>.yaml``; returns whether the file changed (idempotent)."""
    text = render_catalog(build_catalog(lang, root))
    path = catalog_path(lang, root)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def _mtimes(lang: str, root: Path) -> tuple[int, ...]:
    paths = (catalog_path(lang, root), canonical_dir(root) / f"{lang}.yaml", root / "inventory" / f"seeds_{lang}.yaml")
    return tuple(path.stat().st_mtime_ns if path.exists() else -1 for path in paths)


@cache
def _is_current(lang: str, root: Path, mtimes: tuple[int, ...]) -> bool:  # noqa: ARG001 -- mtimes is the cache key
    path = catalog_path(lang, root)
    return path.exists() and path.read_text(encoding="utf-8") == render_catalog(build_catalog(lang, root))


def catalog_is_current(lang: str, root: Path = LAB_ROOT) -> bool:
    """Whether ``catalog_<lang>.yaml`` is byte-for-byte what the importer would write now. Cached on the
    three files it depends on, so a batch of generate calls checks once, and an edit is seen at once."""
    return _is_current(lang, root, _mtimes(lang, root))


def zh_source_coverage(root: Path = LAB_ROOT) -> dict[str, Any]:
    """Catalog-layer proof that every GF0025 source row lands on canonical points, in both directions.

    A row counts as covered only when the set of points the source map names for it *equals* the set of
    canonical points that list the row in ``source_items``. A map that names fewer points than the
    catalogue claims (or more) is a mismatch, not coverage, and so is a point citing a row the map never
    mentions (``orphan_citations``).
    """
    directory = canonical_dir(root)
    source_ids = [row["source_id"] for row in read_yaml(directory / "zh_gf0025_source.yaml")["items"]]
    source_map = {row["source_id"]: set(row["maps_to"]) for row in read_yaml(directory / "zh_source_map.yaml")["items"]}
    listed: dict[str, set[str]] = {}
    for item in load_canonical("zh", root)["items"]:
        for source_id in item.get("source_items", []):
            listed.setdefault(source_id, set()).add(item["id"])
    covered = [sid for sid in source_ids if source_map.get(sid) and source_map[sid] == listed.get(sid)]
    return {
        "total": len(source_ids),
        "covered": len(covered),
        "missing": sorted(set(source_ids) - set(covered)),
        "reciprocal_mismatches": sorted(
            sid for sid in source_ids if source_map.get(sid) and listed.get(sid) and source_map[sid] != listed[sid]
        ),
        "unknown_sources_in_map": sorted(set(source_map) - set(source_ids)),
        "orphan_citations": sorted(set(listed) - set(source_map)),
        "duplicate_source_ids": len(source_ids) - len(set(source_ids)),
    }
