"""Export the writing evaluator's error labels to ``schema/error_tags.json``.

The lab never imports app code (SPEC §1). The labels are read from the app
sources with ``ast.literal_eval``: the closed ``ERROR_CATEGORIES`` tuple of
each language profile, which the evaluator passes to the model as the
``category`` enum and uses to drop any other label.
"""

from __future__ import annotations

import ast
import subprocess
from pathlib import Path
from typing import Any

from grammar_lab.pipeline.jsonio import write_json

# target_lang -> language profile holding ERROR_CATEGORIES, relative to the repository root.
PROFILE_SOURCES = {
    "en": "writing_coach/languages/english/profile.py",
    "zh-Hans": "writing_coach/languages/chinese/profile.py",
}
CONTRACT_SOURCE = "writing_coach/writing_evaluation.py"
CATEGORY_SYMBOL = "ERROR_CATEGORIES"
CONTRACT_SYMBOL = "EVALUATION_SCHEMA_VERSION"


class ExportError(RuntimeError):
    pass


def read_constant(path: Path, symbol: str) -> Any:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == symbol for target in node.targets
        ):
            return ast.literal_eval(node.value)
    raise ExportError(f"{symbol} not found in {path}")


def _last_commit(repo_root: Path, paths: list[str]) -> str | None:
    try:
        completed = subprocess.run(
            ["git", "log", "-1", "--format=%H", "--", *paths],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return completed.stdout.strip() or None


def build_error_tags(repo_root: Path) -> dict[str, Any]:
    languages: dict[str, Any] = {}
    for target_lang, relative in PROFILE_SOURCES.items():
        tags = read_constant(repo_root / relative, CATEGORY_SYMBOL)
        if not isinstance(tags, tuple | list) or not all(isinstance(tag, str) for tag in tags):
            raise ExportError(f"{CATEGORY_SYMBOL} in {relative} is not a sequence of strings")
        languages[target_lang] = {"source_file": relative, "symbol": CATEGORY_SYMBOL, "tags": list(tags)}
    sources = [*PROFILE_SOURCES.values(), CONTRACT_SOURCE]
    return {
        "schema_version": "0.2",
        "engine": "writing_evaluator",
        "engine_contract": read_constant(repo_root / CONTRACT_SOURCE, CONTRACT_SYMBOL),
        "source_commit": _last_commit(repo_root, sources),
        "note": "Generated by `python -m grammar_lab.pipeline.cli export-error-tags`. Do not edit by hand.",
        "languages": languages,
    }


def export_error_tags(repo_root: Path, output: Path) -> dict[str, Any]:
    data = build_error_tags(repo_root)
    write_json(output, data)
    return data
