"""Reading on demand: one content-addressed cache for generated translations, summaries and contextual meanings
(human decision 2026-10-05; docs/project/proposals/READING_ON_DEMAND.md).

A sentence's translation, an article's summary and a word's meaning in its sentence are generated by the AI the
first time any learner asks, and read from here every time after. The primary key is (kind, content_hash,
target_language): the hash is of the normalized text and its language, so the Reader's paragraph and the Sentence
Quick Sheet share one row, and two learners asking at once store one answer (first writer wins).

Privacy. Only PUBLISHED text is ever written here (an `article:<uuid>` content id). Nothing derived from a
learner's own imported text, a book chapter or an anonymous selection reaches this table: those are cached in
process only, because D-104 keeps learner-owned records with the account. There is no account column. No
retention sweep: the rows are derivatives of public content, bounded by the published corpus; created_at is
indexed for a later one.

Review and gate. This file is a PROPOSAL in `migrations/proposed/`, which Alembic does not read, so it is not a
head and triggers no startup refusal. It moves to `migrations/versions/` only after an independent review, the
rehearsal (scripts/product_migration_rehearsal.ps1) and the human's authorization. It is parented on 0027, the
billing proposal; promoted alone, it is re-parented on the head of the day. The application works with the table
absent: answers are cached in process and persistence pauses quietly (writing_coach/reading_derived.py). Startup
never applies it (D-002). `downgrade()` drops the table and every cached answer in it (they are regenerable);
it exists for rehearsal only.

Revision ID: 20261005_0028
Revises: 20261005_0027
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20261005_0028"
down_revision = "20261005_0027"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "reading_derived_texts",
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("target_language", sa.String(16), nullable=False),
        sa.Column("source_language", sa.String(16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(40), nullable=False, server_default=""),
        sa.Column("model", sa.String(160), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("kind", "content_hash", "target_language", name="pk_reading_derived_texts"),
        sa.CheckConstraint("kind IN ('translation', 'summary', 'gloss', 'explanation')", name="ck_reading_derived_kind"),
        sa.CheckConstraint("length(content_hash) = 64", name="ck_reading_derived_hash"),
    )
    op.create_index("ix_reading_derived_texts_created", "reading_derived_texts", ["created_at"])


def downgrade() -> None:
    op.drop_index("ix_reading_derived_texts_created", table_name="reading_derived_texts")
    op.drop_table("reading_derived_texts")
