"""The canonical Reading model's SQLite lifecycle triggers, for the ORM path.

The runtime is PostgreSQL and gets its triggers from migration
`20260924_0016`. The hermetic suite builds SQLite from `Base.metadata`
(`create_all`), which knows nothing about triggers, so `models.py` attaches
these after the tables are created. They are a literal copy of the migration's
`_SQLITE_TRIGGERS` - a migration never imports application code, so the copy
is deliberate - and `tests/test_reading_evidence_schema_parity.py` fails the
moment the two differ.
"""
from __future__ import annotations

SQLITE_TRIGGERS: tuple[str, ...] = (
    "CREATE TRIGGER reading_comprehension_set_insert_guard\n    BEFORE INSERT ON reading_comprehension_sets\n    WHEN NEW.status NOT IN ('draft', 'needs_review')\n    BEGIN SELECT RAISE(ABORT, 'a comprehension set is created undecided and reaches a decision through review'); END",
    "CREATE TRIGGER reading_comprehension_set_delete_guard\n    BEFORE DELETE ON reading_comprehension_sets\n    WHEN OLD.status NOT IN ('draft', 'needs_review', 'rejected')\n    BEGIN SELECT RAISE(ABORT, 'a comprehension set that reached learners is archived, never deleted'); END",
    "CREATE TRIGGER reading_comprehension_set_frozen_guard\n    BEFORE UPDATE ON reading_comprehension_sets\n    WHEN OLD.status NOT IN ('draft', 'needs_review') AND (\n           NEW.article_id IS NOT OLD.article_id\n        OR NEW.language_code IS NOT OLD.language_code\n        OR NEW.support_language IS NOT OLD.support_language\n        OR NEW.article_body_sha256 IS NOT OLD.article_body_sha256\n        OR NEW.generator_version IS NOT OLD.generator_version\n        OR NEW.model IS NOT OLD.model\n        OR NEW.created_at IS NOT OLD.created_at\n        OR NEW.validation_json IS NOT OLD.validation_json\n        OR ((NEW.status IS OLD.status OR NEW.status NOT IN ('approved', 'rejected')) AND (\n               NEW.reviewed_by IS NOT OLD.reviewed_by\n            OR NEW.reviewed_at IS NOT OLD.reviewed_at\n            OR NEW.review_reason IS NOT OLD.review_reason)))\n    BEGIN SELECT RAISE(ABORT, 'a decided comprehension set is frozen: build a new set instead'); END",
    "CREATE TRIGGER reading_comprehension_set_transition_guard\n    BEFORE UPDATE OF status ON reading_comprehension_sets\n    WHEN NEW.status IS NOT OLD.status AND NOT (\n           (OLD.status = 'draft' AND NEW.status = 'needs_review')\n        OR (OLD.status = 'needs_review' AND NEW.status IN ('draft', 'approved', 'rejected'))\n        OR (OLD.status = 'approved' AND NEW.status IN ('stale', 'archived'))\n        OR (OLD.status = 'stale' AND NEW.status IN ('approved', 'archived'))\n        OR (OLD.status = 'archived' AND NEW.status = 'approved'))\n    BEGIN SELECT RAISE(ABORT, 'that comprehension set status change is not a review transition'); END",
    "CREATE TRIGGER reading_comprehension_set_approval_guard\n    BEFORE UPDATE OF status ON reading_comprehension_sets\n    WHEN NEW.status = 'approved' AND OLD.status IS NOT 'approved' AND (\n           (SELECT count(*) FROM reading_comprehension_questions\n             WHERE set_id = NEW.id AND admin_approved) < 1\n        OR (SELECT count(*) FROM reading_comprehension_questions\n             WHERE set_id = NEW.id AND NOT admin_approved AND NOT admin_rejected) > 0)\n    BEGIN SELECT RAISE(ABORT, 'an approved set needs an approved question and no undecided one'); END",
    "CREATE TRIGGER reading_comprehension_set_decision_guard\n    BEFORE UPDATE OF status ON reading_comprehension_sets\n    WHEN NEW.status IS NOT OLD.status AND NEW.status IN ('approved', 'rejected')\n     AND NEW.reviewed_at IS OLD.reviewed_at\n    BEGIN SELECT RAISE(ABORT, 'a decision records its own moment and reviewer'); END",
    "CREATE TRIGGER reading_comprehension_question_insert_guard\n    BEFORE INSERT ON reading_comprehension_questions\n    WHEN (SELECT status FROM reading_comprehension_sets WHERE id = NEW.set_id) NOT IN ('draft', 'needs_review')\n    BEGIN SELECT RAISE(ABORT, 'the questions of a decided comprehension set are frozen'); END",
    "CREATE TRIGGER reading_comprehension_question_update_guard\n    BEFORE UPDATE ON reading_comprehension_questions\n    WHEN (SELECT status FROM reading_comprehension_sets WHERE id = OLD.set_id) NOT IN ('draft', 'needs_review')\n      OR (SELECT status FROM reading_comprehension_sets WHERE id = NEW.set_id) NOT IN ('draft', 'needs_review')\n    BEGIN SELECT RAISE(ABORT, 'the questions of a decided comprehension set are frozen'); END",
    "CREATE TRIGGER reading_comprehension_question_delete_guard\n    BEFORE DELETE ON reading_comprehension_questions\n    WHEN (SELECT status FROM reading_comprehension_sets WHERE id = OLD.set_id) NOT IN ('draft', 'needs_review')\n    BEGIN SELECT RAISE(ABORT, 'the questions of a decided comprehension set are frozen'); END",
    "CREATE TRIGGER reading_comprehension_set_insert_conflict_guard\n    BEFORE INSERT ON reading_comprehension_sets\n    WHEN EXISTS (SELECT 1 FROM reading_comprehension_sets WHERE id = NEW.id)\n    BEGIN SELECT RAISE(ABORT, 'a comprehension set is never replaced'); END",
    "CREATE TRIGGER reading_comprehension_set_update_conflict_guard\n    BEFORE UPDATE ON reading_comprehension_sets\n    WHEN EXISTS (SELECT 1 FROM reading_comprehension_sets\n                  WHERE id <> OLD.id AND (id = NEW.id OR (\n                        status = 'approved' AND NEW.status = 'approved'\n                    AND article_id = NEW.article_id AND support_language = NEW.support_language)))\n    BEGIN SELECT RAISE(ABORT, 'a comprehension set is never replaced'); END",
    "CREATE TRIGGER reading_comprehension_question_insert_conflict_guard\n    BEFORE INSERT ON reading_comprehension_questions\n    WHEN EXISTS (SELECT 1 FROM reading_comprehension_questions WHERE id = NEW.id)\n    BEGIN SELECT RAISE(ABORT, 'a comprehension question is never replaced'); END",
    "CREATE TRIGGER reading_comprehension_question_update_conflict_guard\n    BEFORE UPDATE ON reading_comprehension_questions\n    WHEN NEW.id IS NOT OLD.id\n     AND EXISTS (SELECT 1 FROM reading_comprehension_questions WHERE id = NEW.id)\n    BEGIN SELECT RAISE(ABORT, 'a comprehension question is never replaced'); END",
    "CREATE TRIGGER reading_attempt_insert_guard\n    BEFORE INSERT ON reading_attempts\n    WHEN (SELECT status FROM reading_comprehension_sets WHERE id = NEW.set_id) <> 'approved'\n    BEGIN SELECT RAISE(ABORT, 'a learner meets only an approved comprehension set'); END",
    "CREATE TRIGGER reading_attempt_published_guard\n    BEFORE INSERT ON reading_attempts\n    WHEN (SELECT a.status FROM reading_comprehension_sets s\n            JOIN reading_articles a ON a.id = s.article_id\n           WHERE s.id = NEW.set_id) <> 'published'\n    BEGIN SELECT RAISE(ABORT, 'a learner meets only the published Reading Corpus'); END",
    "CREATE TRIGGER reading_attempt_update_guard\n    BEFORE UPDATE ON reading_attempts\n    BEGIN SELECT RAISE(ABORT, 'a reading attempt is immutable evidence'); END",
    "CREATE TRIGGER reading_attempt_insert_conflict_guard\n    BEFORE INSERT ON reading_attempts\n    WHEN EXISTS (SELECT 1 FROM reading_attempts\n                  WHERE id = NEW.id\n                     OR (user_id = NEW.user_id AND operation_id = NEW.operation_id)\n                     OR (user_id = NEW.user_id AND language_code = NEW.language_code\n                         AND ordinal = NEW.ordinal))\n    BEGIN SELECT RAISE(ABORT, 'a reading attempt is never replaced'); END",
    "CREATE TRIGGER reading_legacy_sessions_read_only_insert\n    BEFORE INSERT ON reading_legacy_sessions\n    BEGIN SELECT RAISE(ABORT, 'the legacy Reading archive is read-only'); END",
    "CREATE TRIGGER reading_legacy_sessions_read_only_update\n    BEFORE UPDATE ON reading_legacy_sessions\n    BEGIN SELECT RAISE(ABORT, 'the legacy Reading archive is read-only'); END",
    "CREATE TRIGGER reading_legacy_attempts_read_only_insert\n    BEFORE INSERT ON reading_legacy_attempts\n    BEGIN SELECT RAISE(ABORT, 'the legacy Reading archive is read-only'); END",
    "CREATE TRIGGER reading_legacy_attempts_read_only_update\n    BEFORE UPDATE ON reading_legacy_attempts\n    BEGIN SELECT RAISE(ABORT, 'the legacy Reading archive is read-only'); END",
)
