/* Builds static/orena/legal/content.js from the legal drafts (docs/legal/DRAFT_{TERMS,PRIVACY,REFUND}.md).

   The drafts are the human's to approve (completion plan item 5); the pages render them as data, so the
   text the human reads in the browser is the text in the drafts, word for word. Run after editing a draft:

     node scripts/build_orena_legal.mjs          writes the file
     node scripts/build_orena_legal.mjs --check  fails if the file is not what the drafts give (the gate)

   Kept: the English section, the Vietnamese section, and the English preamble lines (version, the Chinese
   placeholder, a status line). Every [DECISION: ...] / [OPERATOR] placeholder stays as written. Dropped:
   the draft banner (the page says it is a draft), "Note to counsel" and "Sources in the codebase" - both
   marked "strip before publishing" in the drafts. Inline **bold**, *italic* and `code` become segments, never
   HTML. */
import fs from 'node:fs';

export const DOCS = Object.freeze({ terms: 'TERMS', privacy: 'PRIVACY', refund: 'REFUND' });
const OUT = 'static/orena/legal/content.js';

export function inline(text) {
  const segments = [];
  const pattern = /\*\*([^*]+)\*\*|\*([^*]+)\*|`([^`]+)`/g;
  let last = 0;
  for (const match of text.matchAll(pattern)) {
    if (match.index > last) segments.push({ t: text.slice(last, match.index) });
    if (match[1] != null) segments.push({ t: match[1], b: true });
    else if (match[2] != null) segments.push({ t: match[2], i: true });
    else segments.push({ t: match[3], c: true });
    last = match.index + match[0].length;
  }
  if (last < text.length) segments.push({ t: text.slice(last) });
  return segments;
}

function cells(line) {
  return line.trim().replace(/^\|/, '').replace(/\|$/, '').split('|').map((cell) => inline(cell.trim()));
}

/* Lines of one language's section -> blocks: { p }, { ul: [...] }, { table: { head, rows } }, and sections. */
export function parseSection(lines) {
  const intro = [];
  const sections = [];
  let target = intro;
  let list = null;
  let table = null;
  const close = () => {
    list = null;
    table = null;
  };
  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '');
    if (!line.trim()) {
      close();
      continue;
    }
    const heading = /^##\s+(.*)$/.exec(line);
    if (heading) {
      close();
      const section = { heading: heading[1].trim(), blocks: [] };
      sections.push(section);
      target = section.blocks;
      continue;
    }
    const item = /^[-*]\s+(.*)$/.exec(line);
    if (item) {
      table = null;
      if (!list) {
        list = { ul: [] };
        target.push(list);
      }
      list.ul.push(inline(item[1]));
      continue;
    }
    if (line.trim().startsWith('|')) {
      list = null;
      if (/^\|\s*:?-{3,}/.test(line.trim())) continue;
      if (!table) {
        table = { table: { head: cells(line), rows: [] } };
        target.push(table);
      } else table.table.rows.push(cells(line));
      continue;
    }
    close();
    target.push({ p: inline(line.trim()) });
  }
  return { intro, sections };
}

/* One draft -> { en, vi }. */
export function parseDraft(source) {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const at = (pattern) => lines.findIndex((line) => pattern.test(line));
  const english = at(/^# English\s*$/);
  const vietnamese = at(/^# Tiếng Việt\s*$/);
  if (english < 0 || vietnamese < 0) throw new Error('a draft needs "# English" and "# Tiếng Việt" sections');
  const until = (start) => {
    const end = lines.findIndex((line, index) => index > start && /^---\s*$/.test(line));
    return lines.slice(start + 1, end < 0 ? lines.length : end);
  };
  const title = at(/^# Orena/);
  const firstRule = lines.findIndex((line, index) => index > title && /^---\s*$/.test(line));
  const preamble = lines.slice(title + 1, firstRule).filter((line) => !line.startsWith('>'));
  const en = parseSection(until(english));
  en.intro = [...parseSection(preamble).intro, ...en.intro];
  return { en, vi: parseSection(until(vietnamese)) };
}

export function buildContent(read = (name) => fs.readFileSync(`docs/legal/DRAFT_${name}.md`, 'utf8')) {
  return Object.fromEntries(Object.entries(DOCS).map(([id, name]) => [id, parseDraft(read(name))]));
}

export function moduleText(content) {
  return `/* GENERATED by scripts/build_orena_legal.mjs from docs/legal/DRAFT_*.md - do not edit by hand.
   The legal drafts as data (completion plan item 5, D-128); the human approves the text in the drafts. */
export const LEGAL = Object.freeze(${JSON.stringify(content, null, 1)});
`;
}

const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop());
if (isMain) {
  const text = moduleText(buildContent());
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : '';
    if (current !== text) {
      console.error(`${OUT} is not what the drafts give: run node scripts/build_orena_legal.mjs`);
      process.exit(1);
    }
    console.log(`${OUT} matches the drafts`);
  } else {
    fs.mkdirSync('static/orena/legal', { recursive: true });
    fs.writeFileSync(OUT, text);
    console.log(`wrote ${OUT}`);
  }
}
