/* Builds static/orena/shell/surfaces.css (PUB-4, D-16W): inside every solid surface the learner UI draws, the text tokens
   the backdrop adjusts for text that sits directly on the photo (--muted, --text3, --accent-on-photo) go back to the base
   tokens, because a card, panel, sheet, menu or input has its own opaque ground where the base tokens already pass AA.

   The list is derived, not typed: every selector, in kit/shell/screens CSS, whose rule gives the element a single solid ground
   (`background: var(--surface|surface2|surface3|bg|accent-soft|...)`). `node scripts/build_backdrop_surfaces.mjs` rewrites the
   file; scripts/test_orena_kit.mjs fails if the file is stale, so a new card class can never ship without the reset. */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const ROOT = 'static/orena';
const OUT = path.join(ROOT, 'shell/surfaces.css');
const GROUNDS = ['surface', 'surface2', 'surface3', 'bg', 'accent-soft', 'ai-soft', 'green-soft', 'red-soft', 'amber-soft', 'support-soft', 'tint2'];
const GROUND = new RegExp(`(^|;)\\s*background(-color)?\\s*:\\s*var\\(--(${GROUNDS.join('|')})\\)\\s*(!important\\s*)?(;|$)`);
// Elements that carry the adjusted tokens themselves, or paint the photo: never reset.
const SCOPES = new Set(['.o-frame', '.a-shell', '.o-main', '.a-main', '.s-onboarding']);
// Form controls draw their own ground in every browser.
const CONTROLS = ['input', 'textarea', 'select', 'dialog', '[role="dialog"]', '[role="menu"]', '[role="listbox"]', '[role="tooltip"]'];

function strip(css) {
  return css.replace(/\/\*[\s\S]*?\*\//g, '');
}

function splitTop(text, separator) {
  const parts = [];
  let depth = 0;
  let quote = '';
  let start = 0;
  for (let i = 0; i < text.length; i += 1) {
    const c = text[i];
    if (quote) {
      if (c === quote && text[i - 1] !== '\\') quote = '';
    } else if (c === '"' || c === "'") quote = c;
    else if (c === '(' || c === '[') depth += 1;
    else if (c === ')' || c === ']') depth -= 1;
    else if (c === separator && depth === 0) {
      parts.push(text.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(text.slice(start));
  return parts;
}

/* Leaf rules (selector, body), descending into @media / @supports / @layer, skipping @keyframes and @font-face. */
function rules(css) {
  const out = [];
  const walk = (text) => {
    let i = 0;
    while (i < text.length) {
      const open = text.indexOf('{', i);
      if (open < 0) break;
      const head = text.slice(i, open).trim();
      let depth = 1;
      let j = open + 1;
      while (j < text.length && depth > 0) {
        if (text[j] === '{') depth += 1;
        else if (text[j] === '}') depth -= 1;
        j += 1;
      }
      const body = text.slice(open + 1, j - 1);
      if (head.startsWith('@')) {
        if (/^@(media|supports|layer|container)/.test(head)) walk(body);
      } else {
        out.push({ selector: head.replace(/^[;}\s]+/, ''), body });
      }
      i = j;
    }
  };
  walk(strip(css));
  return out;
}

function files(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return ['vendor', 'public', 'fonts'].includes(entry.name) ? [] : files(full);
    return entry.name.endsWith('.css') ? [full] : [];
  });
}

export function surfaceSelectors() {
  const found = new Set();
  for (const file of files(ROOT).sort()) {
    const normalised = file.replace(/\\/g, '/');
    if (normalised.endsWith('kit/tokens.css') || normalised.endsWith('shell/surfaces.css')) continue;
    for (const { selector, body } of rules(fs.readFileSync(file, 'utf8'))) {
      if (!GROUND.test(body)) continue;
      for (const one of splitTop(selector, ',').map((s) => s.trim())) {
        if (!one || one.includes('::') || /^(:root|html|body)$/.test(one) || SCOPES.has(one)) continue;
        // A bare backdrop scope with state is still a scope.
        if ([...SCOPES].some((scope) => one === scope || one.endsWith(` ${scope}`))) continue;
        found.add(one);
      }
    }
  }
  return [...found, ...CONTROLS].sort();
}

export function buildSurfacesCss() {
  const selectors = surfaceSelectors();
  const lines = selectors.map((s) => `  ${s}`);
  return `/* GENERATED by scripts/build_backdrop_surfaces.mjs - do not edit; scripts/test_orena_kit.mjs fails if it is stale.

   Inside a solid surface (a card, panel, sheet, menu, input: any element that sets its own opaque ground) the text tokens the
   backdrop adjusts for text set directly on the photo go back to the base tokens (kit/tokens.css), where they already pass AA
   on that ground. Only text that sits on the photo or on the glass keeps the adjusted values (PUB-4, D-16W). */
:root {
  --muted-base: var(--muted);
  --text3-base: var(--text3);
}
:where(
${lines.join(',\n')}
) {
  --muted: var(--muted-base);
  --text3: var(--text3-base);
  --accent-on-photo: var(--accent);
}
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  fs.writeFileSync(OUT, buildSurfacesCss());
  console.log(`wrote ${OUT} (${surfaceSelectors().length} selectors)`);
}
