"""Fetch the interface fonts from Google Fonts once and write them under static/orena/fonts/ (PUB-2, D-162).

Orena serves its own fonts, so a visitor's browser never contacts Google to render a page. This script is how the
files were produced; it is not run by the app or by CI. The families, weights and styles below are exactly what
templates/orena/index.html and the public pages requested before the change. Google's CSS API returns the
variable-font files sliced by unicode-range (latin, latin-ext, vietnamese, and for the Noto SC faces one slice per
block of Han characters); each slice is saved once and `fonts.css` declares it with its unicode-range, so a
browser downloads only the slices a page needs.

    python scripts/fetch_self_hosted_fonts.py

The licence text of every family (SIL Open Font License 1.1) is fetched from the google/fonts repository.
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "static" / "orena" / "fonts"
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

# (css family query, google/fonts licence folder)
FAMILIES = [
    ("Fredoka:wght@500;600", "fredoka"),
    ("Outfit:wght@400;500;600;700", "outfit"),
    ("Plus+Jakarta+Sans:wght@400;500;600;700", "plusjakartasans"),
    ("Literata:ital,opsz,wght@0,7..72,400;0,7..72,500;0,7..72,600;1,7..72,400;1,7..72,500", "literata"),
    ("JetBrains+Mono:wght@400;500", "jetbrainsmono"),
    ("Noto+Sans+SC:wght@400;500;600;700", "notosanssc"),
    ("Noto+Serif+SC:wght@300;400;500", "notoserifsc"),
]


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "licences").mkdir(exist_ok=True)
    faces: list[dict] = []
    for query, folder in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={query}&display=swap").decode("utf-8")
        for m in re.finditer(r"(?:/\*\s*([^*]+?)\s*\*/\s*)?@font-face\s*\{([^}]*)\}", css):
            body = m.group(2)
            fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
            style = re.search(r"font-style:\s*(\w+)", body).group(1)
            weight = int(re.search(r"font-weight:\s*(\d+)", body).group(1))
            url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
            rng = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()
            # Latin faces are labelled in a comment; the Noto SC slices are numbered in the file name (.N.woff2).
            label = m.group(1) or "slice-" + re.search(r"\.(\d+)\.woff2$", url).group(1)
            faces.append({"fam": fam, "style": style, "weight": weight, "url": url, "range": rng, "label": label})
        lic = get(f"https://raw.githubusercontent.com/google/fonts/main/ofl/{folder}/OFL.txt")
        (OUT / "licences" / f"OFL-{folder}.txt").write_bytes(lic)
        print(f"{folder}: licence saved")

    # One file per distinct (url): a variable font serves several weights from the same file.
    by_url: dict[str, dict] = {}
    for f in faces:
        e = by_url.setdefault(f["url"], {**f, "weights": set()})
        e["weights"].add(f["weight"])
    css_out = [
        "/* Interface fonts, served from this origin (PUB-2, D-162). Generated by scripts/fetch_self_hosted_fonts.py.",
        "   SIL Open Font License 1.1: see licences/. Each @font-face carries its unicode-range, so a page",
        "   downloads only the slices it uses. */",
    ]
    total = 0
    for i, (url, e) in enumerate(sorted(by_url.items(), key=lambda kv: (kv[1]["fam"], kv[1]["style"], kv[1]["label"]))):
        label = re.sub(r"[^a-z0-9]+", "-", e["label"].lower()).strip("-")
        name = f"{slug(e['fam'])}-{e['style']}-{label}.woff2"
        data = get(url)
        (OUT / name).write_bytes(data)
        total += len(data)
        w = sorted(e["weights"])
        weight = f"{w[0]} {w[-1]}" if len(w) > 1 else str(w[0])
        css_out.append(
            f"@font-face{{font-family:'{e['fam']}';font-style:{e['style']};font-weight:{weight};font-display:swap;"
            f"src:url({name}) format('woff2');unicode-range:{e['range']}}}"
        )
    (OUT / "fonts.css").write_text("\n".join(css_out) + "\n", encoding="utf-8")
    print(f"{len(by_url)} files, {total} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
