"""Measure the lightest and darkest region of each backdrop photo as it appears in the app (PUB-4, D-16W).

Writes scripts/fixtures/backdrop_extremes.json, which scripts/test_orena_kit.mjs reads to prove WCAG AA for
every text token on the glass chrome and on the page veil in both themes. Needs Pillow (not a project
dependency: `pip install pillow` in a scratch environment). Run after any change to the photos or to the
scrim in static/orena/kit/tokens.css; the test fails if a photo's sha256 no longer matches the fixture.

The effective backdrop is the photo (cover, centred) under the design's scrim at --bd-strength (Orena.dc.html
body[data-backdrop=on]). The chrome blurs it (blur(18px)), so its region is measured after a Gaussian blur of
sigma 18; the page is measured after sigma 12 (about one line of text).
"""
import hashlib
import json
import math
import pathlib
import sys

from PIL import Image, ImageFilter

ROOT = pathlib.Path(__file__).resolve().parent.parent
BG = ROOT / 'static/orena/public/bg'
STRENGTH = 0.6
SCRIM = {
    'dark': ((12, 10, 22), [(0, .86), (.55, .62), (1, .22)]),
    'light': ((250, 247, 240), [(0, .82), (.55, .55), (1, .12)]),
}


def lin(c):
    s = c / 255
    return s / 12.92 if s <= .03928 else ((s + .055) / 1.055) ** 2.4


def lum(rgb):
    return .2126 * lin(rgb[0]) + .7152 * lin(rgb[1]) + .0722 * lin(rgb[2])


def scrim_alpha(theme, t):
    stops = SCRIM[theme][1]
    t = min(max(t, 0), 1)
    for (p0, a0), (p1, a1) in zip(stops, stops[1:], strict=False):
        if t <= p1:
            return a0 + (a1 - a0) * (t - p0) / (p1 - p0)
    return stops[-1][1]


def effective(theme, device):
    name = ('midnight' if theme == 'dark' else 'paper') + ('-wide' if device == 'desktop' else '-tall')
    img = Image.open(BG / f'{name}.jpg').convert('RGB')
    w, h = (1920, 1080) if device == 'desktop' else (390, 844)
    s = max(w / img.width, h / img.height)
    nw, nh = round(img.width * s), round(img.height * s)
    img = img.resize((nw, nh), Image.BILINEAR)
    left, top = (nw - w) // 2, (nh - h) // 2
    img = img.crop((left, top, left + w, top + h))
    colour = SCRIM[theme][0]
    px = img.load()
    out = Image.new('RGB', (w, h))
    po = out.load()
    for y in range(h):
        for x in range(w):
            a = scrim_alpha(theme, math.hypot((x / w - .56) / 1.10, (y / h - .46) / .85)) * STRENGTH
            po[x, y] = tuple(round(c * (1 - a) + k * a) for c, k in zip(px[x, y], colour, strict=True))
    return name, out, w, h


def extremes(img, box):
    lo = hi = None
    for rgb in img.crop(box).getdata():
        value = lum(rgb)
        if hi is None or value > hi[0]:
            hi = (value, rgb)
        if lo is None or value < lo[0]:
            lo = (value, rgb)
    return list(hi[1]), list(lo[1])


def main():
    out = {'_note': 'Generated by scripts/measure_backdrop_extremes.py. Do not edit by hand.', 'strength': STRENGTH, 'regions': {}}
    for theme in ('dark', 'light'):
        for device in ('desktop', 'mobile'):
            name, img, w, h = effective(theme, device)
            sha = hashlib.sha256((BG / f'{name}.jpg').read_bytes()).hexdigest()
            regions = [('page', 12, (0, 0, w, h))]
            if device == 'desktop':
                regions += [('rail', 18, (0, 0, 232, h)), ('topbar', 18, (232, 0, w, 64))]
            else:
                regions += [('bar', 18, (12, h - 90, w - 12, h - 18)), ('chips', 18, (0, 0, w, 130))]
            for region, sigma, box in regions:
                hi, lo = extremes(img.filter(ImageFilter.GaussianBlur(sigma)), box)
                key = f'{theme}/page/{device}' if region == 'page' else f'{theme}/{region}'
                out['regions'][key] = {'photo': name, 'sha256': sha, 'sigma': sigma, 'lightest': hi, 'darkest': lo}
    target = ROOT / 'scripts/fixtures/backdrop_extremes.json'
    target.write_text(json.dumps(out, indent=1) + '\n', encoding='utf-8')
    print(f'wrote {target}')


if __name__ == '__main__':
    sys.exit(main())
