"""The canonical Reading live end-to-end run (D-075 §12, D-076) - over HTTP.

Drives a running Orena the way an administrator and a learner would, and
checks each step against what the canonical model promises. It writes real
rows (an article per language, its approved comprehension set and, when
learner submit is on, an attempt), so it runs against the **admin sandbox
only**: ports 8000 (production) and 8010 (preview) are refused.

    python scripts/reading_canonical_e2e.py run    --base-url http://localhost:8012 \\
        --state backups/reading-e2e.json [--ai-provider gemini --ai-model gemini-3.5-flash-lite]
    # recreate the runtime: containers down and up, volumes kept
    python scripts/reading_canonical_e2e.py verify --base-url http://localhost:8012 \\
        --state backups/reading-e2e.json

`run`, per learning language (English and Chinese by default):

1. Admin imports an article, the worker processes it, the Admin reviews it and
   publishes it - the publish response and audit carry the rights warnings.
2. A comprehension set is generated by the configured AI provider, every
   question decided, the set approved.
3. The learner meets the set without its answers. With learner submit off
   (the D-076 default) a submit answers 503 and writes nothing, and the run
   stops there - it proves the gate, not the flow. With submit on:
4. the attempt persists; ability moves; the next article is chosen by the
   selection policy, the same way twice;
5. a retried submit (same operation id) returns the same attempt and ability
   moves once;
6. a fresh client (a reload) sees the attempt and the ability unchanged;
7. an edit to the article body stales the set; the attempt is still evidence
   and the set's questions are unchanged;
8. Collection, Learner Summary, the cross-skill cue, Admin Activity and
   product analytics read the canonical attempt.

`verify`, after the runtime is recreated, checks that all of it is still true.

Authentication: with OAuth off (local development) nothing is needed. With it
on, put the signed `writing_coach_session` cookie of an administrator's
session in `ORENA_E2E_SESSION` - the environment, never the command line - and
the learner is that account. Nothing here prints it.

Exit status is 0 only when every check passed.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import uuid
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import requests

REFUSED_PORTS = {8000, 8010}
COOKIE = "writing_coach_session"
PASSAGES = {
    "en": (
        "The night bus to the coast leaves the station at eleven. Mai bought her ticket an hour early "
        "because the evening buses are often full on Fridays. She sat near the window and watched the city "
        "lights disappear behind the hills. When the bus stopped at a small village, an old man got on with "
        "a basket of oranges and offered one to every passenger. By sunrise they reached the sea, and Mai "
        "decided that the long journey had been worth it.\n\n"
        "Later she wrote to her brother that the kindness of a stranger had made the trip."
    ),
    "zh": (
        "开往海边的夜班车晚上十一点从车站出发。小梅提前一个小时买了车票，因为星期五晚上的车常常坐满了人。"
        "她坐在窗边，看着城市的灯光慢慢消失在山后。汽车在一个小村子停下的时候，一位老人提着一篮橘子上了车，"
        "给每位乘客送了一个。天亮的时候，他们到了海边，小梅觉得这趟长途旅行很值得。\n\n"
        "后来她给哥哥写信说，是一位陌生人的善意让这次旅行变得难忘。"
    ),
}
EDIT = {"en": " The return trip was quieter.", "zh": "回来的路上安静多了。"}


class Failed(AssertionError):
    pass


class Run:
    def __init__(self, base_url: str) -> None:
        self.base = base_url.rstrip("/")
        self.passed = 0
        self.failures: list[str] = []
        self.http = self._client()

    def _client(self) -> requests.Session:
        client = requests.Session()
        client.headers["Origin"] = self.base
        cookie = os.getenv("ORENA_E2E_SESSION", "").strip()
        if cookie:
            host = urlparse(self.base).hostname or "localhost"
            client.cookies.set(COOKIE, cookie, domain=host)
        return client

    def reload(self) -> None:
        """A fresh client carrying only what a page reload keeps: the cookies."""
        cookies = self.http.cookies.copy()
        self.http = self._client()
        self.http.cookies.update(cookies)

    def call(self, method: str, path: str, *, expect: int | set[int] = 200, **kwargs: Any) -> Any:
        response = self.http.request(method, f"{self.base}{path}", timeout=180, **kwargs)
        wanted = {expect} if isinstance(expect, int) else expect
        if response.status_code not in wanted:
            raise Failed(f"{method} {path} answered {response.status_code}, expected {sorted(wanted)}: "
                         f"{response.text[:300]}")
        try:
            return response.json()
        except ValueError:
            return None

    def check(self, label: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.passed += 1
            print(f"  ok   {label}")
        else:
            self.failures.append(f"{label} {detail}".strip())
            print(f"  FAIL {label} {detail}".rstrip())

    @staticmethod
    def category(body: Any) -> str:
        detail = (body or {}).get("detail") if isinstance(body, dict) else None
        return str(detail.get("category") if isinstance(detail, dict) else detail or "")


def _refused(base_url: str) -> str | None:
    parsed = urlparse(base_url)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        return "--base-url must be the sandbox's http(s) URL"
    if parsed.port in REFUSED_PORTS:
        return f"port {parsed.port} is production or preview - they keep every gate (D-076)"
    return None


def _wait_for_article(run: Run, job_id: str, timeout: float) -> str:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        job = run.call("GET", f"/api/admin/reading/jobs/{job_id}")
        if job.get("result_article_id"):
            return job["result_article_id"]
        if job.get("status") in {"failed", "cancelled"}:
            raise Failed(f"the import job ended {job.get('status')}: {job.get('last_error_code')}")
        time.sleep(1.0)
    raise Failed("the import job was not processed - is the Reading worker running "
                 "(python -m writing_coach.reading_worker)?")


def _one_language(run: Run, language: str, nonce: str, *, worker_timeout: float) -> dict[str, Any]:
    print(f"[{language}] admin: import, review, publish")
    run.call("POST", "/api/platform/language", json={"language": language})
    title = f"E2E canonical Reading {language} {nonce}"
    body = PASSAGES[language] + f"\n\n({nonce})"
    job = run.call("POST", "/api/admin/reading/jobs", expect=202,
                   data={"kind": "text", "text": body, "title": title, "language": language})
    article_id = _wait_for_article(run, job["id"], worker_timeout)
    article = run.call("GET", f"/api/admin/reading/articles/{article_id}")
    run.check("the import is a candidate, not published", article["status"] != "published", article["status"])
    run.check("the body is stored as submitted", article["body"].strip() == body.strip())
    published = run.call("POST", f"/api/admin/reading/articles/{article_id}/status", json={"status": "published"})
    warnings = {item["code"] for item in published.get("publication_warnings", [])}
    run.check("publishing without rights answers warns, and publishes", published["status"] == "published"
              and {"rights_unknown", "attribution_unknown"} <= warnings, str(sorted(warnings)))
    events = run.call("GET", f"/api/admin/reading/articles/{article_id}").get("events") or []
    run.check("the review trail records the override beside its warnings", any(
        (item.get("changes") or {}).get("published_over_warnings") for item in events))

    print(f"[{language}] admin: comprehension set")
    practice = run.call("GET", "/api/reading/practice/next")
    support = practice.get("support_language") or "vi"
    created = run.call("POST", f"/api/admin/reading/articles/{article_id}/comprehension-sets", expect=201,
                       json={"support_language": support})
    set_id = created["id"]
    run.check("the processor wrote a grounded draft", created["status"] == "draft" and len(created["questions"]) >= 3
              and all(q["evidence_text"] is None or article["body"][q["evidence_start"]:q["evidence_end"]]
                      == q["evidence_text"] for q in created["questions"]))
    run.call("POST", f"/api/admin/reading/comprehension-sets/{set_id}/status", json={"status": "needs_review"})
    for question in created["questions"]:
        run.call("POST", f"/api/admin/reading/comprehension-sets/{set_id}/questions/{question['id']}",
                 json={"decision": "approve"})
    approved = run.call("POST", f"/api/admin/reading/comprehension-sets/{set_id}/status",
                        json={"status": "approved"})
    run.check("the Admin approved the set", approved["status"] == "approved")
    key = {question["id"]: question["correct_index"] for question in approved["questions"]}

    print(f"[{language}] learner")
    served = run.call("GET", f"/api/reading/practice/articles/{article_id}")
    questions = served["set"]["questions"]
    run.check("the learner meets the approved set", served["set"]["id"] == set_id and len(questions) == len(key))
    run.check("and never its answers", not any({"correct_index", "explanation", "evidence_text"} & set(q)
                                                for q in questions))
    # Every question right but the first: a real score, not a perfect one.
    answers = {q["id"]: (key[q["id"]] if index else (key[q["id"]] + 1) % len(q["options"]))
               for index, q in enumerate(questions)}
    state: dict[str, Any] = {"language": language, "article_id": article_id, "set_id": set_id,
                             "support_language": support, "submit_enabled": served["submit_enabled"],
                             "questions": {q_id: index for q_id, index in key.items()}}
    before_evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
    if not served["submit_enabled"]:
        refused = run.call("POST", "/api/reading/practice/attempts", expect=503,
                           json={"set_id": set_id, "operation_id": f"e2e-{nonce}-{language}", "answers": answers})
        run.check("learner submit is off: 503 reading_submit_disabled", run.category(refused) ==
                  "reading_submit_disabled")
        after = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
        run.check("and it wrote nothing", len(after) == len(before_evidence))
        return state

    operation = f"e2e-{nonce}-{language}"
    ability_before = run.call("GET", "/api/reading/practice/ability")
    first = run.call("POST", "/api/reading/practice/attempts",
                     json={"set_id": set_id, "operation_id": operation, "answers": answers})
    attempt = first["attempt"]
    run.check("the attempt persisted", first["status"] == "committed" and not first["replayed"])
    run.check("it was scored against the approved key",
              attempt["correct_count"] == len(questions) - 1 and attempt["total"] == len(questions))
    run.check("the answer key came back only after saving", len(first["results"]) == len(questions)
              and all(item["correct_index"] == key[item["question_id"]] for item in first["results"]))
    ability = run.call("GET", "/api/reading/practice/ability")
    run.check("ability counted the attempt", ability["attempts"] == ability_before["attempts"] + 1)
    retry = run.call("POST", "/api/reading/practice/attempts",
                     json={"set_id": set_id, "operation_id": operation, "answers": answers})
    run.check("a retried submit is the same attempt", retry["replayed"] and retry["attempt"]["id"] == attempt["id"])
    after_retry = run.call("GET", "/api/reading/practice/ability")
    run.check("and ability moved once", after_retry == ability)
    next_one = run.call("GET", "/api/reading/practice/next")
    run.check("the next article is chosen the same way twice", next_one == run.call("GET", "/api/reading/practice/next"))
    run.check("never the one just read", not next_one["available"] or next_one["next"]["article_id"] != article_id)
    if next_one["available"]:
        run.check("under the selection policy", next_one["next"]["selection_policy_version"] == "reading-select/1")

    run.reload()
    run.call("POST", "/api/platform/language", json={"language": language})
    evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
    run.check("after a reload the attempt is there", any(item["id"] == attempt["id"] for item in evidence))
    run.check("and the ability is unchanged", run.call("GET", "/api/reading/practice/ability") == ability)

    print(f"[{language}] edit the article body")
    edited = run.call("POST", f"/api/admin/reading/articles/{article_id}", json={"body": article["body"] + EDIT[language]})
    run.check("the edit was saved", edited["body"].endswith(EDIT[language]))
    after_edit = run.call("GET", f"/api/admin/reading/comprehension-sets/{set_id}")
    run.check("the set is stale", after_edit["status"] == "stale" and after_edit["anchored"] is False)
    run.check("its questions are unchanged", {q["id"]: q["correct_index"] for q in after_edit["questions"]} == key)
    events = run.call("GET", f"/api/admin/reading/articles/{article_id}").get("events") or []
    run.check("the review trail says why", any(item.get("action") == "comprehension_set_stale" for item in events))
    run.call("GET", f"/api/reading/practice/articles/{article_id}", expect=404)
    replay = run.call("POST", "/api/reading/practice/attempts",
                      json={"set_id": set_id, "operation_id": operation, "answers": answers})
    run.check("the recorded attempt still answers its retry", replay["replayed"] and replay["attempt"]["id"] == attempt["id"])
    late = run.call("POST", "/api/reading/practice/attempts", expect=422,
                    json={"set_id": set_id, "operation_id": operation + "-late", "answers": answers})
    run.check("a new answer against the old text is refused", run.category(late) == "reading_set_stale")
    evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
    run.check("the attempt is still evidence", any(item["id"] == attempt["id"] for item in evidence))

    print(f"[{language}] consumers")
    collection = run.call("GET", "/api/collection")
    run.check("Collection lists the article", any(
        entry["ref"] == {"domain": "reading", "id": article_id} for entry in collection.get("entries", [])))
    summary = run.call("GET", "/api/learner-summary")
    reading = (summary.get("domains") or {}).get("reading") or {}
    run.check("Learner Summary reads the attempt", any(
        item["ref"]["id"] == attempt["id"] for item in reading.get("observations", [])))
    run.call("GET", "/api/cross-skill-cue")
    run.check("the cross-skill cue reads canonical evidence without error", True)
    activity = run.call("GET", "/api/admin/product-activity?window_days=7")
    reading_skill = next((row for row in activity.get("skills", []) if row.get("skill") == "reading"), {})
    run.check("analytics counts the Reading attempt", reading_skill.get("activities", 0) >= 1, str(reading_skill))
    state |= {"operation_id": operation, "answers": answers, "attempt_id": attempt["id"], "ability": ability,
              "edited_body_suffix": EDIT[language]}
    return state


def _admin_activity(run: Run) -> None:
    users = run.call("GET", "/api/admin/console/users?sort=active&limit=10", expect={200, 503})
    if not isinstance(users, dict) or not users.get("items"):
        run.check("Admin Activity lists accounts", False, "no accounts readable")
        return
    for item in users["items"]:
        detail = run.call("GET", f"/api/admin/console/users/{item['id']}")
        counts = {row["measure"]: row["count"] for row in detail.get("activity", [])}
        if counts.get("reading_attempts"):
            run.check("Admin Activity counts canonical Reading attempts", True)
            return
    run.check("Admin Activity counts canonical Reading attempts", False)


def run_all(args: argparse.Namespace) -> int:
    run = Run(args.base_url)
    me = run.call("GET", "/api/me")
    print(f"target {run.base} ({me.get('mode', 'session')} auth)")
    if args.ai_provider:
        run.call("PUT", "/api/admin/ai/config", json={"provider": args.ai_provider, "model": args.ai_model})
        print(f"AI provider selected: {args.ai_provider}")
    nonce = uuid.uuid4().hex[:8]
    states = []
    try:
        for language in args.language or ["en", "zh"]:
            states.append(_one_language(run, language, nonce, worker_timeout=args.worker_timeout))
        if any(state.get("attempt_id") for state in states):
            _admin_activity(run)
    except Failed as exc:
        run.failures.append(str(exc))
        print(f"  FAIL {exc}")
    Path(args.state).parent.mkdir(parents=True, exist_ok=True)
    Path(args.state).write_text(json.dumps({"base_url": run.base, "nonce": nonce, "languages": states},
                                           ensure_ascii=False, indent=2), encoding="utf-8")
    return _report(run, args.state)


def verify(args: argparse.Namespace) -> int:
    run = Run(args.base_url)
    saved = json.loads(Path(args.state).read_text(encoding="utf-8"))
    print(f"target {run.base}: verifying {args.state} after the runtime was recreated")
    try:
        for state in saved["languages"]:
            language = state["language"]
            run.call("POST", "/api/platform/language", json={"language": language})
            article = run.call("GET", f"/api/admin/reading/articles/{state['article_id']}")
            run.check(f"[{language}] the article is still published", article["status"] == "published")
            found = run.call("GET", f"/api/admin/reading/comprehension-sets/{state['set_id']}")
            run.check(f"[{language}] its set's questions are unchanged",
                      {q["id"]: q["correct_index"] for q in found["questions"]} == state["questions"])
            if not state.get("attempt_id"):
                run.check(f"[{language}] the set is still approved", found["status"] == "approved")
                continue
            run.check(f"[{language}] the set is still stale", found["status"] == "stale")
            evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
            run.check(f"[{language}] the attempt is still evidence",
                      any(item["id"] == state["attempt_id"] for item in evidence))
            run.check(f"[{language}] the ability is unchanged",
                      run.call("GET", "/api/reading/practice/ability") == state["ability"])
            replay = run.call("POST", "/api/reading/practice/attempts",
                              json={"set_id": state["set_id"], "operation_id": state["operation_id"],
                                    "answers": state["answers"]})
            run.check(f"[{language}] a retry still returns the same attempt",
                      replay["replayed"] and replay["attempt"]["id"] == state["attempt_id"])
    except Failed as exc:
        run.failures.append(str(exc))
        print(f"  FAIL {exc}")
    return _report(run, args.state)


def _report(run: Run, state: str) -> int:
    print()
    print(f"{run.passed} checks passed, {len(run.failures)} failed. State: {state}")
    for failure in run.failures:
        print(f"  - {failure}")
    return 0 if not run.failures else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("command", choices=("run", "verify"))
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--state", default="backups/reading-e2e.json")
    parser.add_argument("--language", action="append", choices=("en", "zh"))
    parser.add_argument("--ai-provider", default="")
    parser.add_argument("--ai-model", default="")
    parser.add_argument("--worker-timeout", type=float, default=120.0)
    args = parser.parse_args(argv)
    reason = _refused(args.base_url)
    if reason:
        print(f"refused: {reason}")
        return 2
    return run_all(args) if args.command == "run" else verify(args)


if __name__ == "__main__":
    sys.exit(main())
