"""The canonical Reading live end-to-end run (D-075 §12, D-076) - over HTTP.

Drives a running Orena the way an administrator and a learner would, and
checks each step against what the canonical model promises. It writes real
rows (three articles per language, their approved comprehension sets and, when
learner submit is on, attempts), so it runs against the **admin sandbox
only**: the base URL must be a loopback address on a port other than 8000
(production) and 8010 (preview), and the server must not report itself as
production (`/api/readiness`).

    python scripts/reading_canonical_e2e.py run    --base-url http://localhost:8012 \\
        --state backups/reading-e2e.json [--ai-provider gemini --ai-model gemini-3.5-flash-lite]
    # recreate the runtime: containers down and up, volumes kept
    python scripts/reading_canonical_e2e.py verify --base-url http://localhost:8012 \\
        --state backups/reading-e2e.json

`run`, per learning language (English and Chinese by default):

1. Admin imports three articles, the worker processes them, the Admin reviews
   and publishes them - the publish response and audit carry the rights
   warnings. A set cannot be built before publishing.
2. For each, a comprehension set is generated by the configured AI provider,
   every question decided, the set approved.
3. The learner meets a set without its answers, and the selection policy
   (`/api/reading/practice/next`, what Home's "for you" rail shows) must offer
   an article - the run fails when it offers none. With learner submit off
   (the D-076 default) a submit answers 503 and writes nothing, and the run
   stops there - it proves the gate, not the flow. With submit on:
4. the recommended article is answered first without its recommendation -
   opened some other way - and records no selection; then with the signed
   recommendation `/next` issued, and records the policy's version although
   the evidence moved in between; a request that states provenance itself is
   refused; the next choice moves on;
5. the learner answers an article they picked themselves: the attempt
   persists with no selection recorded, and ability moves;
6. a retried submit (same operation id) returns the same attempt and ability
   moves once;
7. a fresh client (a reload) sees the attempts and the ability unchanged;
8. an edit to the article body stales the set; the attempt is still evidence
   and the set's questions are unchanged;
9. Collection and Learner Summary read the attempt; the cross-skill cue names
   this run's attempt and article; Admin Activity, for this exact account
   (`account_id` from the ability projection), counts exactly this run's
   attempts in this language more than before; product analytics - which by
   design names no learner - counts exactly that many more Reading activities
   and completions than before. The sandbox should have no other learner
   active while it runs.

`verify`, after the runtime is recreated, checks that all of it is still true.

Authentication: with OAuth off (local development) nothing is needed. With it
on, put the signed `writing_coach_session` cookie of an administrator's
session in `ORENA_E2E_SESSION` - the environment, never the command line - and
the learner is that account. Nothing here prints it. The account should have
no pending writing review: the cross-skill cue prefers one to Reading, and the
run reports that rather than passing over it.

Exit status is 0 only when every check passed.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import os
import sys
import time
import uuid
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import requests

REFUSED_PORTS = {8000, 8010}
SELECTION_POLICY = "reading-select/1"
ARTICLES_PER_LANGUAGE = 3
COOKIE = "writing_coach_session"
PASSAGES = {
    "en": (
        "The night bus to the coast leaves the station at eleven. Mai bought her ticket an hour early "
        "because the evening buses are often full on Fridays. She sat near the window and watched the city "
        "lights disappear behind the hills. When the bus stopped at a small village, an old man got on with "
        "a basket of oranges and offered one to every passenger. By sunrise they reached the sea, and Mai "
        "decided that the long journey had been worth it.\n\n"
        "Later she wrote to her brother that the kindness of a stranger had made the trip."
    ),
    "zh": (
        "开往海边的夜班车晚上十一点从车站出发。小梅提前一个小时买了车票，因为星期五晚上的车常常坐满了人。"
        "她坐在窗边，看着城市的灯光慢慢消失在山后。汽车在一个小村子停下的时候，一位老人提着一篮橘子上了车，"
        "给每位乘客送了一个。天亮的时候，他们到了海边，小梅觉得这趟长途旅行很值得。\n\n"
        "后来她给哥哥写信说，是一位陌生人的善意让这次旅行变得难忘。"
    ),
}
EDIT = {"en": " The return trip was quieter.", "zh": "回来的路上安静多了。"}


class Failed(AssertionError):
    pass


class Run:
    def __init__(self, base_url: str) -> None:
        self.base = base_url.rstrip("/")
        self.passed = 0
        self.failures: list[str] = []
        self.http = self._client()

    def _client(self) -> requests.Session:
        client = requests.Session()
        client.headers["Origin"] = self.base
        cookie = os.getenv("ORENA_E2E_SESSION", "").strip()
        if cookie:
            host = urlparse(self.base).hostname or "localhost"
            client.cookies.set(COOKIE, cookie, domain=host)
        return client

    def reload(self) -> None:
        """A fresh client carrying only what a page reload keeps: the cookies."""
        cookies = self.http.cookies.copy()
        self.http = self._client()
        self.http.cookies.update(cookies)

    def call(self, method: str, path: str, *, expect: int | set[int] = 200, **kwargs: Any) -> Any:
        response = self.http.request(method, f"{self.base}{path}", timeout=180, **kwargs)
        wanted = {expect} if isinstance(expect, int) else expect
        if response.status_code not in wanted:
            raise Failed(f"{method} {path} answered {response.status_code}, expected {sorted(wanted)}: "
                         f"{response.text[:300]}")
        try:
            return response.json()
        except ValueError:
            return None

    def check(self, label: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.passed += 1
            print(f"  ok   {label}")
        else:
            self.failures.append(f"{label} {detail}".strip())
            print(f"  FAIL {label} {detail}".rstrip())

    def require(self, label: str, condition: bool, detail: str = "") -> None:
        """A check the rest of the run depends on: failing it stops the language."""
        self.check(label, condition, detail)
        if not condition:
            raise Failed(f"{label} - required, stopping {detail}".rstrip())

    @staticmethod
    def category(body: Any) -> str:
        detail = (body or {}).get("detail") if isinstance(body, dict) else None
        return str(detail.get("category") if isinstance(detail, dict) else detail or "")


def _loopback(host: str) -> bool:
    if host.casefold() == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


def _refused(base_url: str) -> str | None:
    """Static: the URL alone. `_server_refused` asks the server itself."""
    parsed = urlparse(base_url)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        return "--base-url must be the sandbox's http(s) URL"
    if parsed.port in REFUSED_PORTS:
        return f"port {parsed.port} is production or preview - they keep every gate (D-076)"
    if not _loopback(parsed.hostname):
        return (f"{parsed.hostname} is not this machine: the sandbox is reached on a loopback address, "
                "and a public hostname may be production (D-076)")
    return None


def _server_refused(run: Run) -> str | None:
    readiness = run.call("GET", "/api/readiness", expect={200, 503}) or {}
    environment = str(readiness.get("environment") or "").strip().casefold()
    if environment == "production":
        return "the server reports APP_ENV=production - this run is for the admin sandbox only (D-076)"
    return None


def _wait_for_article(run: Run, job_id: str, timeout: float) -> str:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        job = run.call("GET", f"/api/admin/reading/jobs/{job_id}")
        if job.get("result_article_id"):
            return job["result_article_id"]
        if job.get("status") in {"failed", "cancelled"}:
            raise Failed(f"the import job ended {job.get('status')}: {job.get('last_error_code')}")
        time.sleep(1.0)
    raise Failed("the import job was not processed - is the Reading worker running "
                 "(python -m writing_coach.reading_worker)?")


def _published_with_set(run: Run, language: str, nonce: str, index: int, support: str, *,
                        worker_timeout: float, checked: bool) -> dict[str, Any]:
    """Import, review, publish, then build and approve the set - D-075's order.
    `checked` runs the admin-side checks once per language."""
    title = f"E2E canonical Reading {language} {nonce}-{index}"
    body = PASSAGES[language] + f"\n\n({nonce}-{index})"
    job = run.call("POST", "/api/admin/reading/jobs", expect=202,
                   data={"kind": "text", "text": body, "title": title, "language": language})
    article_id = _wait_for_article(run, job["id"], worker_timeout)
    article = run.call("GET", f"/api/admin/reading/articles/{article_id}")
    if checked:
        run.check("the import is a candidate, not published", article["status"] != "published", article["status"])
        run.check("the body is stored as submitted", article["body"].strip() == body.strip())
        early = run.call("POST", f"/api/admin/reading/articles/{article_id}/comprehension-sets", expect=409,
                         json={"support_language": support})
        run.check("a candidate gets no comprehension set: publish first",
                  run.category(early) == "reading_article_not_published")
    published = run.call("POST", f"/api/admin/reading/articles/{article_id}/status", json={"status": "published"})
    if checked:
        warnings = {item["code"] for item in published.get("publication_warnings", [])}
        run.check("publishing without rights answers warns, and publishes", published["status"] == "published"
                  and {"rights_unknown", "attribution_unknown"} <= warnings, str(sorted(warnings)))
        events = run.call("GET", f"/api/admin/reading/articles/{article_id}").get("events") or []
        run.check("the review trail records the override beside its warnings", any(
            (item.get("changes") or {}).get("published_over_warnings") for item in events))
    created = run.call("POST", f"/api/admin/reading/articles/{article_id}/comprehension-sets", expect=201,
                       json={"support_language": support})
    set_id = created["id"]
    run.check(f"the processor wrote a grounded draft ({index})",
              created["status"] == "draft" and len(created["questions"]) >= 3
              and all(q["evidence_text"] is None or article["body"][q["evidence_start"]:q["evidence_end"]]
                      == q["evidence_text"] for q in created["questions"]))
    run.call("POST", f"/api/admin/reading/comprehension-sets/{set_id}/status", json={"status": "needs_review"})
    for question in created["questions"]:
        run.call("POST", f"/api/admin/reading/comprehension-sets/{set_id}/questions/{question['id']}",
                 json={"decision": "approve"})
    approved = run.call("POST", f"/api/admin/reading/comprehension-sets/{set_id}/status",
                        json={"status": "approved"})
    run.check(f"the Admin approved the set ({index})", approved["status"] == "approved")
    return {"article_id": article_id, "set_id": set_id, "body": article["body"],
            "key": {question["id"]: question["correct_index"] for question in approved["questions"]}}


def _key(run: Run, set_id: str) -> dict[str, int]:
    """The Admin's view of any approved set - the policy may choose an article
    this run did not write."""
    found = run.call("GET", f"/api/admin/reading/comprehension-sets/{set_id}")
    return {question["id"]: question["correct_index"] for question in found["questions"]}


def _sheet(run: Run, article_id: str, key: dict[str, int], *, one_wrong: bool) -> tuple[str, dict[str, int], int]:
    served = run.call("GET", f"/api/reading/practice/articles/{article_id}")
    questions = served["set"]["questions"]
    run.check("the learner meets the approved set without its answers", len(questions) == len(key) and not any(
        {"correct_index", "explanation", "evidence_text"} & set(q) for q in questions))
    # Every question right but the first: a real score, not a perfect one.
    answers = {q["id"]: ((key[q["id"]] + 1) % len(q["options"]) if one_wrong and not index else key[q["id"]])
               for index, q in enumerate(questions)}
    return served["set"]["id"], answers, len(questions)


def _choice(offer: dict[str, Any]) -> dict[str, Any]:
    """`/next` without its recommendation, which carries the moment it was
    issued: the same choice a second later is signed differently."""
    found = dict(offer)
    if isinstance(found.get("next"), dict):
        found["next"] = {key: value for key, value in found["next"].items() if key != "recommendation"}
    return found


def _account_attempts(run: Run, account_id: str, language: str) -> int:
    """Admin Activity's canonical Reading count for exactly this account."""
    detail = run.call("GET", f"/api/admin/console/users/{account_id}")
    return sum(int(row["count"]) for row in detail.get("activity", [])
               if row.get("measure") == "reading_attempts" and row.get("language") == language)


def _analytics(run: Run) -> tuple[int, int]:
    activity = run.call("GET", "/api/admin/product-activity?window_days=7")
    reading = next((row for row in activity.get("skills", []) if row.get("skill") == "reading"), {})
    return int(reading.get("activities", 0)), int(reading.get("completions", 0))


def _one_language(run: Run, language: str, nonce: str, *, worker_timeout: float) -> dict[str, Any]:
    print(f"[{language}] admin: import, review, publish, comprehension sets")
    run.call("POST", "/api/platform/language", json={"language": language})
    support = run.call("GET", "/api/reading/practice/next").get("support_language") or "vi"
    articles = [
        _published_with_set(run, language, nonce, index, support, worker_timeout=worker_timeout, checked=not index)
        for index in range(ARTICLES_PER_LANGUAGE)
    ]
    ours = {item["article_id"]: item for item in articles}

    print(f"[{language}] learner: the selection policy")
    offered = run.call("GET", "/api/reading/practice/next")
    run.require("the selection policy offers a next article", bool(offered.get("available")), str(offered)[:200])
    choice = offered["next"]
    run.check("under the selection policy", choice["selection_policy_version"] == SELECTION_POLICY)
    run.check("the same inputs choose the same article",
              _choice(offered) == _choice(run.call("GET", "/api/reading/practice/next")))
    run.check("and it comes with a signed recommendation", str(choice.get("recommendation", "")).startswith("rr1."))
    run.check("and offer its set without answers", not any(
        {"correct_index", "explanation", "evidence_text"} & set(q) for q in choice["set"]["questions"]))
    state: dict[str, Any] = {"language": language, "support_language": support,
                             "articles": [{"article_id": item["article_id"], "set_id": item["set_id"],
                                           "questions": item["key"]} for item in articles]}
    before_evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
    first = articles[0]
    set_id, answers, _ = _sheet(run, first["article_id"], first["key"], one_wrong=True)
    served = run.call("GET", f"/api/reading/practice/articles/{first['article_id']}")
    state["submit_enabled"] = served["submit_enabled"]
    if not served["submit_enabled"]:
        refused = run.call("POST", "/api/reading/practice/attempts", expect=503,
                           json={"set_id": set_id, "operation_id": f"e2e-{nonce}-{language}", "answers": answers})
        run.check("learner submit is off: 503 reading_submit_disabled",
                  run.category(refused) == "reading_submit_disabled")
        after = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
        run.check("and it wrote nothing", len(after) == len(before_evidence))
        return state

    # Exact identity and baselines, before this run's first attempt.
    ability_start = run.call("GET", "/api/reading/practice/ability")
    account_id = ability_start["account_id"]
    admin_before = _account_attempts(run, account_id, language)
    analytics_before = _analytics(run)
    made = 0

    # -- the article the policy recommended -------------------------------
    chosen_key = ours[choice["article_id"]]["key"] if choice["article_id"] in ours else _key(run, choice["set_id"])
    chosen_set, chosen_answers, _ = _sheet(run, choice["article_id"], chosen_key, one_wrong=False)
    run.check("the offered set is the one the learner meets", chosen_set == choice["set_id"])
    claimed = run.call("POST", "/api/reading/practice/attempts", expect=422,
                       json={"set_id": chosen_set, "operation_id": f"e2e-{nonce}-{language}-claim",
                             "answers": chosen_answers, "selection_policy_version": SELECTION_POLICY})
    run.check("a request cannot state provenance itself", bool(claimed))
    independent = run.call("POST", "/api/reading/practice/attempts",
                           json={"set_id": chosen_set, "operation_id": f"e2e-{nonce}-{language}-independent",
                                 "answers": chosen_answers})
    made += 1
    run.check("the recommended article opened some other way is the learner's own choice",
              independent["status"] == "committed" and independent["attempt"]["selection_policy_version"] is None,
              str(independent["attempt"].get("selection_policy_version")))
    selected_operation = f"e2e-{nonce}-{language}-selected"
    selected = run.call("POST", "/api/reading/practice/attempts",
                        json={"set_id": chosen_set, "operation_id": selected_operation, "answers": chosen_answers,
                              "recommendation": choice["recommendation"]})
    made += 1
    run.require("the attempt presenting the recommendation persisted", selected["status"] == "committed")
    run.check("the server recorded the recommendation it issued, though evidence moved in between",
              selected["attempt"]["selection_policy_version"] == SELECTION_POLICY,
              str(selected["attempt"]["selection_policy_version"]))
    moved = run.call("GET", "/api/reading/practice/next")
    run.check("the next choice moves on from the article just read",
              not moved["available"] or moved["next"]["article_id"] != choice["article_id"])
    state |= {"selected": {"article_id": choice["article_id"], "set_id": chosen_set,
                           "operation_id": selected_operation, "answers": chosen_answers,
                           "recommendation": choice["recommendation"],
                           "attempt_id": selected["attempt"]["id"]},
              "independent_attempt_id": independent["attempt"]["id"]}

    # -- an article the learner picked -------------------------------------
    now_offered = moved["next"]["article_id"] if moved["available"] else None
    picked = next((item for item in articles
                   if item["article_id"] not in {choice["article_id"], now_offered}), None)
    run.require("one of this run's articles is neither read nor offered", picked is not None)
    article_id, key = picked["article_id"], picked["key"]
    set_id, answers, total = _sheet(run, article_id, key, one_wrong=True)
    operation = f"e2e-{nonce}-{language}"
    ability_before = run.call("GET", "/api/reading/practice/ability")
    first_try = run.call("POST", "/api/reading/practice/attempts",
                         json={"set_id": set_id, "operation_id": operation, "answers": answers})
    made += 1
    attempt = first_try["attempt"]
    run.check("the attempt persisted", first_try["status"] == "committed" and not first_try["replayed"])
    run.check("a picked article records no selection", attempt["selection_policy_version"] is None,
              str(attempt["selection_policy_version"]))
    run.check("it was scored against the approved key", attempt["correct_count"] == total - 1
              and attempt["total"] == total)
    run.check("the answer key came back only after saving", len(first_try["results"]) == total
              and all(item["correct_index"] == key[item["question_id"]] for item in first_try["results"]))
    ability = run.call("GET", "/api/reading/practice/ability")
    run.check("ability counted the attempt", ability["attempts"] == ability_before["attempts"] + 1)
    retry = run.call("POST", "/api/reading/practice/attempts",
                     json={"set_id": set_id, "operation_id": operation, "answers": answers})
    run.check("a retried submit is the same attempt", retry["replayed"] and retry["attempt"]["id"] == attempt["id"])
    run.check("and ability moved once", run.call("GET", "/api/reading/practice/ability") == ability)

    run.reload()
    run.call("POST", "/api/platform/language", json={"language": language})
    evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
    run.check("after a reload all three attempts are there",
              {attempt["id"], selected["attempt"]["id"], independent["attempt"]["id"]}
              <= {item["id"] for item in evidence})
    run.check("and the ability is unchanged", run.call("GET", "/api/reading/practice/ability") == ability)

    print(f"[{language}] edit the article body")
    edited = run.call("POST", f"/api/admin/reading/articles/{article_id}", json={"body": picked["body"] + EDIT[language]})
    run.check("the edit was saved", edited["body"].endswith(EDIT[language]))
    after_edit = run.call("GET", f"/api/admin/reading/comprehension-sets/{set_id}")
    run.check("the set is stale", after_edit["status"] == "stale" and after_edit["anchored"] is False)
    run.check("its questions are unchanged", {q["id"]: q["correct_index"] for q in after_edit["questions"]} == key)
    events = run.call("GET", f"/api/admin/reading/articles/{article_id}").get("events") or []
    run.check("the review trail says why", any(item.get("action") == "comprehension_set_stale" for item in events))
    run.call("GET", f"/api/reading/practice/articles/{article_id}", expect=404)
    replay = run.call("POST", "/api/reading/practice/attempts",
                      json={"set_id": set_id, "operation_id": operation, "answers": answers})
    run.check("the recorded attempt still answers its retry", replay["replayed"] and replay["attempt"]["id"] == attempt["id"])
    late = run.call("POST", "/api/reading/practice/attempts", expect=422,
                    json={"set_id": set_id, "operation_id": operation + "-late", "answers": answers})
    run.check("a new answer against the old text is refused", run.category(late) == "reading_set_stale")
    evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
    run.check("the attempt is still evidence", any(item["id"] == attempt["id"] for item in evidence))

    print(f"[{language}] consumers")
    collection = run.call("GET", "/api/collection")
    run.check("Collection lists the article", any(
        entry["ref"] == {"domain": "reading", "id": article_id} for entry in collection.get("entries", [])))
    summary = run.call("GET", "/api/learner-summary")
    reading = (summary.get("domains") or {}).get("reading") or {}
    run.check("Learner Summary reads the attempt", any(
        item["ref"]["id"] == attempt["id"] for item in reading.get("observations", [])))
    _check_cue(run, language, attempt_id=attempt["id"], article_id=article_id)
    admin_after = _account_attempts(run, account_id, language)
    run.check(f"Admin Activity counts exactly this run's {made} attempts for this account and language",
              admin_after - admin_before == made, f"{admin_before} -> {admin_after}")
    analytics_after = _analytics(run)
    run.check(f"analytics counts exactly {made} more Reading activities and completions",
              (analytics_after[0] - analytics_before[0], analytics_after[1] - analytics_before[1]) == (made, made),
              f"{analytics_before} -> {analytics_after}")
    state |= {"account_id": account_id, "admin_reading_attempts": admin_after, "article_id": article_id, "set_id": set_id, "operation_id": operation, "answers": answers,
              "attempt_id": attempt["id"], "ability": ability, "questions": key,
              "edited_body_suffix": EDIT[language]}
    return state


def _check_cue(run: Run, language: str, *, attempt_id: str, article_id: str) -> None:
    """The cue must be this run's Reading attempt - its newest - not merely
    answer without error."""
    cue = run.call("GET", "/api/cross-skill-cue")
    if cue.get("source") == "writing":
        run.check(f"[{language}] the cross-skill cue names this run's Reading attempt", False,
                  "a pending writing review takes precedence for this account - run with one that has none")
        return
    provenance = cue.get("provenance") or {}
    action = cue.get("action") or {}
    run.check(f"[{language}] the cross-skill cue names this run's Reading attempt",
              cue.get("available") is True and cue.get("source") == "reading"
              and provenance.get("attempt_id") == attempt_id and provenance.get("record_id") == article_id
              and provenance.get("language") == language
              and action.get("kind") == "reading" and action.get("article_id") == article_id,
              json.dumps(cue, ensure_ascii=False)[:300])


def _guard_server(run: Run) -> int | None:
    reason = _server_refused(run)
    if reason:
        print(f"refused: {reason}")
        return 2
    return None


def run_all(args: argparse.Namespace) -> int:
    run = Run(args.base_url)
    refused = _guard_server(run)
    if refused is not None:
        return refused
    me = run.call("GET", "/api/me")
    print(f"target {run.base} ({me.get('mode', 'session')} auth)")
    if args.ai_provider:
        run.call("PUT", "/api/admin/ai/config", json={"provider": args.ai_provider, "model": args.ai_model})
        print(f"AI provider selected: {args.ai_provider}")
    nonce = uuid.uuid4().hex[:8]
    states = []
    for language in args.language or ["en", "zh"]:
        try:
            states.append(_one_language(run, language, nonce, worker_timeout=args.worker_timeout))
        except Failed as exc:
            run.failures.append(str(exc))
            print(f"  FAIL {exc}")
    Path(args.state).parent.mkdir(parents=True, exist_ok=True)
    Path(args.state).write_text(json.dumps({"base_url": run.base, "nonce": nonce, "languages": states},
                                           ensure_ascii=False, indent=2), encoding="utf-8")
    return _report(run, args.state)


def verify(args: argparse.Namespace) -> int:
    run = Run(args.base_url)
    refused = _guard_server(run)
    if refused is not None:
        return refused
    saved = json.loads(Path(args.state).read_text(encoding="utf-8"))
    print(f"target {run.base}: verifying {args.state} after the runtime was recreated")
    try:
        for state in saved["languages"]:
            language = state["language"]
            run.call("POST", "/api/platform/language", json={"language": language})
            for item in state.get("articles", []):
                article = run.call("GET", f"/api/admin/reading/articles/{item['article_id']}")
                run.check(f"[{language}] the article is still published", article["status"] == "published")
                found = run.call("GET", f"/api/admin/reading/comprehension-sets/{item['set_id']}")
                run.check(f"[{language}] its set's questions are unchanged",
                          {q["id"]: q["correct_index"] for q in found["questions"]} == item["questions"])
                expected = "stale" if item["article_id"] == state.get("article_id") else "approved"
                run.check(f"[{language}] its set is still {expected}", found["status"] == expected)
            if not state.get("attempt_id"):
                continue
            evidence = run.call("GET", "/api/reading/practice/evidence?limit=100")["items"]
            run.check(f"[{language}] all three attempts are still evidence",
                      {state["attempt_id"], state["selected"]["attempt_id"], state["independent_attempt_id"]}
                      <= {item["id"] for item in evidence})
            run.check(f"[{language}] Admin Activity still counts this account's attempts",
                      _account_attempts(run, state["account_id"], language) == state["admin_reading_attempts"])
            run.check(f"[{language}] the ability is unchanged",
                      run.call("GET", "/api/reading/practice/ability") == state["ability"])
            replay = run.call("POST", "/api/reading/practice/attempts",
                              json={"set_id": state["set_id"], "operation_id": state["operation_id"],
                                    "answers": state["answers"]})
            run.check(f"[{language}] a retry still returns the same attempt",
                      replay["replayed"] and replay["attempt"]["id"] == state["attempt_id"])
            chosen = state["selected"]
            replay = run.call("POST", "/api/reading/practice/attempts",
                              json={"set_id": chosen["set_id"], "operation_id": chosen["operation_id"],
                                    "answers": chosen["answers"], "recommendation": chosen["recommendation"]})
            run.check(f"[{language}] the policy's choice is still recorded as the policy's",
                      replay["replayed"] and replay["attempt"]["id"] == chosen["attempt_id"]
                      and replay["attempt"]["selection_policy_version"] == SELECTION_POLICY)
            _check_cue(run, language, attempt_id=state["attempt_id"], article_id=state["article_id"])
    except Failed as exc:
        run.failures.append(str(exc))
        print(f"  FAIL {exc}")
    return _report(run, args.state)


def _report(run: Run, state: str) -> int:
    print()
    print(f"{run.passed} checks passed, {len(run.failures)} failed. State: {state}")
    for failure in run.failures:
        print(f"  - {failure}")
    return 0 if not run.failures else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("command", choices=("run", "verify"))
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--state", default="backups/reading-e2e.json")
    parser.add_argument("--language", action="append", choices=("en", "zh"))
    parser.add_argument("--ai-provider", default="")
    parser.add_argument("--ai-model", default="")
    parser.add_argument("--worker-timeout", type=float, default=120.0)
    args = parser.parse_args(argv)
    reason = _refused(args.base_url)
    if reason:
        print(f"refused: {reason}")
        return 2
    return run_all(args) if args.command == "run" else verify(args)


if __name__ == "__main__":
    sys.exit(main())
