"""Regenerate static/orena/kit/icons.js from the official lucide-static release.

The new learner UI (D-088) uses the Lucide icon family at one pinned release.
Every path comes from the package, never typed by hand: the design's own SVGs
are partly hand-typed variants of Lucide icons, so each one was identified by
name and is rendered from the package instead (Design Contract rule 46).

Run it when an icon is added to NAMES or the release is re-pinned:

    python scripts/sync_lucide_icons.py

It downloads the release tarball from the npm registry, reads icons/<name>.svg
for every name below, and writes the inner markup of each into icons.js. CI
never runs it (no network); `scripts/test_orena_kit.mjs` checks the generated
file's header, that every name here is present, and that the new UI only asks
for names that exist.
"""

from __future__ import annotations

import io
import json
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

RELEASE = "0.525.0"
ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "static" / "orena" / "kit" / "icons.js"

# Every icon the pinned design draws (docs/design/canonical-ui/screens), by
# Lucide name, plus the ones the product adds from the same package when a
# drawn component needs them. Keep sorted.
NAMES = sorted(
    {
        "arrow-left",
        "arrow-left-right",
        "arrow-right",
        "arrow-up",
        "arrow-up-right",
        "audio-lines",
        "ban",
        "bell",
        "book-open",
        "bookmark",
        "bookmark-check",
        "case-lower",
        "chart-column",
        "check",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "chevron-up",
        "circle",
        "circle-alert",
        "circle-check",
        "circle-x",
        "clock",
        "clock-4",
        "compass",
        "credit-card",
        "crown",
        "ellipsis",
        "eye",
        "flame",
        "git-branch",
        "graduation-cap",
        "headphones",
        "highlighter",
        "history",
        "house",
        "inbox",
        "info",
        "keyboard",
        "languages",
        "layout-grid",
        "library-big",
        "lightbulb",
        "link",
        "list",
        "list-filter",
        "lock",
        "message-square",
        "messages-square",
        "mic",
        "moon",
        "notebook-pen",
        "panels-top-left",
        "pause",
        "pen-line",
        "pencil",
        "play",
        "puzzle",
        "quote",
        "refresh-cw",
        "repeat",
        "reply",
        "rotate-ccw",
        "rotate-cw",
        "search",
        "skip-back",
        "skip-forward",
        "square",
        "square-check-big",
        "star",
        "sun",
        "sun",
        "tags",
        "target",
        "timer",
        "upload",
        "volume-2",
        "whole-word",
        "x",
        "zap",
    }
)

SVG = re.compile(r"<svg\b[^>]*>(.*?)</svg>", re.S)


def fetch(release: str) -> dict[str, str]:
    url = f"https://registry.npmjs.org/lucide-static/-/lucide-static-{release}.tgz"
    data = urllib.request.urlopen(url, timeout=60).read()
    found: dict[str, str] = {}
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        for member in tar.getmembers():
            match = re.fullmatch(r"package/icons/([a-z0-9-]+)\.svg", member.name)
            if not match:
                continue
            svg = tar.extractfile(member).read().decode("utf-8")
            inner = SVG.search(svg).group(1)
            found[match.group(1)] = " ".join(line.strip() for line in inner.strip().splitlines())
    return found


def main() -> int:
    icons = fetch(RELEASE)
    missing = [name for name in NAMES if name not in icons]
    if missing:
        print("not in lucide-static", RELEASE, ":", ", ".join(missing), file=sys.stderr)
        return 1
    body = ",\n".join(f"  {json.dumps(name)}: {json.dumps(icons[name])}" for name in NAMES)
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        "/* GENERATED by scripts/sync_lucide_icons.py - do not edit by hand.\n"
        f"   lucide-static@{RELEASE} (ISC licence, https://lucide.dev) - the one icon family of\n"
        "   the learner design (D-088, Design Contract rule 46). Paths are the package's own. */\n"
        f"export const LUCIDE_RELEASE = {json.dumps(RELEASE)};\n\n"
        "export const ICONS = Object.freeze({\n"
        f"{body},\n"
        "});\n\n"
        "/* An icon as inline SVG: 24x24 viewBox, stroke 2, drawn in currentColor. `size` is the\n"
        "   rendered box in px, as the frame gives it. Unknown names throw: an icon the design\n"
        "   uses is added to scripts/sync_lucide_icons.py, never typed here. */\n"
        "export function icon(name, { size = 20, stroke = 2, label = '' } = {}) {\n"
        "  const inner = ICONS[name];\n"
        "  if (!inner) throw new Error(`Unknown icon: ${name}`);\n"
        "  const a11y = label ? `role=\"img\" aria-label=\"${String(label).replace(/\"/g, '&quot;')}\"` : 'aria-hidden=\"true\"';\n"
        "  return `<svg class=\"ic\" width=\"${size}\" height=\"${size}\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"${stroke}\" stroke-linecap=\"round\" stroke-linejoin=\"round\" ${a11y}>${inner}</svg>`;\n"
        "}\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {TARGET.relative_to(ROOT)}: {len(NAMES)} icons from lucide-static@{RELEASE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
