import assert from 'node:assert/strict';
import { openMedia } from '../static/orena/product/media-source.js';
import { setRemovedImports } from '../static/orena/product/import-removed.js';
let calls = 0;
const payload = {asset:{asset_id:'source-session',processing_state:'ready'},transcript:{segments:[{original_text:'你好'}]},translations:[{translated_meaning:'Xin chào'}]};
const api = {mediaMy: async (id, support) => {calls++; assert.equal(support,'vi'); return payload;}, listeningLibraryLesson: async () => {calls++; return payload;}};
const opts = {api,owner:'learner-a',language:'zh',support:'vi'};
await Promise.all([openMedia('upload:source-session',opts),openMedia('source-session',opts)]);
assert.equal(calls,1,'workspace aliases and simultaneous opens share one server request');
assert.equal(await openMedia('source-session',opts),payload);
await openMedia('source-session',{...opts,owner:'learner-b'});
assert.equal(calls,2,'another account must load its own record');
setRemovedImports(['upload:source-session']);
await assert.rejects(openMedia('source-session',opts), {status:404});
setRemovedImports([]);
let resolve;
const slowApi = {mediaMy: () => new Promise(done => {resolve = done;})};
const slowOpts = {...opts,api:slowApi};
const first = openMedia('upload:source-wait',slowOpts);
await Promise.resolve();
const second = openMedia('source-wait',slowOpts);
setRemovedImports(['upload:source-wait']);
resolve(payload);
await assert.rejects(first,{status:404});
await assert.rejects(second,{status:404});
setRemovedImports([]);
console.log('Media session scope, support and deletion: PASS');
