import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {replaySegment,segmentPlaybackDelayMs} from '../static/orena/capabilities/media-player.js';
import {transcriptTokens} from '../static/orena/capabilities/transcript-tokens.js';
assert.equal(segmentPlaybackDelayMs(1000,2000,1),1090);
assert.equal(segmentPlaybackDelayMs(1000,2000,1.25),890);
assert.equal(segmentPlaybackDelayMs(1000,1000,1),null);
assert.deepEqual(transcriptTokens("Hello, I’m learning English.").filter(x=>x.word).map(x=>x.text),['Hello','I’m','learning','English']);
assert.deepEqual(transcriptTokens('大家好，我是刘芬 AI').filter(x=>x.word).map(x=>x.text),['大','家','好','我','是','刘','芬','AI']);
const commands=[];
const frame={src:'https://www.youtube-nocookie.com/embed/abcdefghijk?enablejsapi=1',contentWindow:{postMessage(message,origin){commands.push({payload:JSON.parse(message),origin});}}};
const root={querySelector(selector){return selector==='#orenaMedia'?frame:null;}};
const playback={provider:'youtube',kind:'embed',url:'https://www.youtube-nocookie.com/embed/abcdefghijk'};
assert.equal(replaySegment(root,playback,1000,1010,1),true);
await new Promise(resolve=>setTimeout(resolve,130));
assert.deepEqual(commands.map(x=>x.payload.func),['seekTo','playVideo','pauseVideo']);
console.log('Media playback and transcript tokens: PASS');
